LOC_DIR=src/dsdt/platform
LIB=DSDT

include $(PRJ_PATH)/make/config.mk

SRC_LIST=$(wildcard *.c)

include $(PRJ_PATH)/make/components.mk
include $(PRJ_PATH)/make/defs.mk
include $(PRJ_PATH)/make/target.mk

all: dep obj