/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17821 2009-11-11 09:00:00Z dts12 $
 */
#ifndef JWSDOT1QVLANSTATICTABLE_H
#define JWSDOT1QVLANSTATICTABLE_H

/* function declarations */
void init_jwsDot1qVlanStaticTable(void);
void initialize_table_jwsDot1qVlanStaticTable(void);
Netsnmp_Node_Handler jwsDot1qVlanStaticTable_handler;
Netsnmp_First_Data_Point  jwsDot1qVlanStaticTable_get_first_data_point;
Netsnmp_Next_Data_Point   jwsDot1qVlanStaticTable_get_next_data_point;

/* column number definitions for table jwsDot1qVlanStaticTable */
       #define COLUMN_JWSDOT1QVLANINDEX		1
       #define COLUMN_JWSDOT1QVLANID		2
       #define COLUMN_JWSDOT1QVLANNAME		3
       #define COLUMN_JWSDOT1QVLANEGRESSPORTS		4
       #define COLUMN_JWSDOT1QVLANTAGGEDPORTS		5
       #define COLUMN_JWSDOT1QVLANROWSTATUS		6
#endif /* JWSDOT1QVLANSTATICTABLE_H */
