/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef JWSDEVGENERAL_H
#define JWSDEVGENERAL_H

/* function declarations */
void init_jwsDevGeneral(void);
Netsnmp_Node_Handler handle_jwsDevModelName;
Netsnmp_Node_Handler handle_jwsDevModelId;
Netsnmp_Node_Handler handle_jwsSysDescription;
Netsnmp_Node_Handler handle_jwsSysName;
Netsnmp_Node_Handler handle_jwsSysLocation;
Netsnmp_Node_Handler handle_jwsSysUptime;
Netsnmp_Node_Handler handle_jwsHardwareVersion;
Netsnmp_Node_Handler handle_jwsBootloaderVersion;
Netsnmp_Node_Handler handle_jwsSoftwareVersion;
Netsnmp_Node_Handler handle_jwsResetSystemAction;
Netsnmp_Node_Handler handle_jwsSaveConfigAction;
Netsnmp_Node_Handler handle_jwsSaveConfigStatus;
Netsnmp_Node_Handler handle_jwsClearConfigAction;
Netsnmp_Node_Handler handle_jwsClearConfigStatus;
Netsnmp_Node_Handler handle_jwsPowerSupplyStatus;

#endif /* JWSDEVGENERAL_H */
