/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef JWSDEVFACTORYINFO_H
#define JWSDEVFACTORYINFO_H

/* function declarations */
void init_jwsDevFactoryInfo(void);
Netsnmp_Node_Handler handle_jwsSerialNumber;
Netsnmp_Node_Handler handle_jwsBurnedInMacAddress;

#endif /* JWSDEVFACTORYINFO_H */
