/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17821 2009-11-11 09:00:00Z dts12 $
 */
#ifndef JWSIFEXTETHSTATSTABLE_H
#define JWSIFEXTETHSTATSTABLE_H

/* function declarations */
void init_jwsIfExtEthStatsTable(void);
void initialize_table_jwsIfExtEthStatsTable(void);
Netsnmp_Node_Handler jwsIfExtEthStatsTable_handler;
Netsnmp_First_Data_Point  jwsIfExtEthStatsTable_get_first_data_point;
Netsnmp_Next_Data_Point   jwsIfExtEthStatsTable_get_next_data_point;

/* column number definitions for table jwsIfExtEthStatsTable */
       #define COLUMN_JWSIFEXTETHSTATSIFINDEX		1
       #define COLUMN_JWSIFEXTETHSTATSCLEAR		2
       #define COLUMN_JWSIFEXTETHSTATSRXBYTES		3
       #define COLUMN_JWSIFEXTETHSTATSRXUCASTPKTS		4
       #define COLUMN_JWSIFEXTETHSTATSRXBCASTPKTS		5
       #define COLUMN_JWSIFEXTETHSTATSRXMCASTPKTS		6
       #define COLUMN_JWSIFEXTETHSTATSRXPAUSEPKTS		7
       #define COLUMN_JWSIFEXTETHSTATSTXBYTES		8
       #define COLUMN_JWSIFEXTETHSTATSTXUCASTPKTS		9
       #define COLUMN_JWSIFEXTETHSTATSTXBCASTPKTS		10
       #define COLUMN_JWSIFEXTETHSTATSTXMCASTPKTS		11
       #define COLUMN_JWSIFEXTETHSTATSTXPAUSEPKTS		12
#endif /* JWSIFEXTETHSTATSTABLE_H */
