/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef JWSJRPPGLOBALGROUP_H
#define JWSJRPPGLOBALGROUP_H

/* function declarations */
void init_jwsJrppGlobalGroup(void);
Netsnmp_Node_Handler handle_jwsJrppAdminStatus;
Netsnmp_Node_Handler handle_jwsJrppRingNumber;

#endif /* JWSJRPPGLOBALGROUP_H */
