/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17821 2009-11-11 09:00:00Z dts12 $
 */
#ifndef JWSJRPPRINGTABLE_H
#define JWSJRPPRINGTABLE_H

/* function declarations */
void init_jwsJrppRingTable(void);
void initialize_table_jwsJrppRingTable(void);
Netsnmp_Node_Handler jwsJrppRingTable_handler;
Netsnmp_First_Data_Point  jwsJrppRingTable_get_first_data_point;
Netsnmp_Next_Data_Point   jwsJrppRingTable_get_next_data_point;

/* column number definitions for table jwsJrppRingTable */
       #define COLUMN_JWSJRPPRINGINDEX		1
       #define COLUMN_JWSJRPPRINGID		2
       #define COLUMN_JWSJRPPRINGENABLESTATUS		3
       #define COLUMN_JWSJRPPRINGNODEPRIORITY		4
       #define COLUMN_JWSJRPPRINGPRIMARYPORT		5
       #define COLUMN_JWSJRPPRINGSECONDARYPORT		6
       #define COLUMN_JWSJRPPRINGROWSTATUS		7
#endif /* JWSJRPPRINGTABLE_H */
