/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef JWSPAGSTATICCONFIG_H
#define JWSPAGSTATICCONFIG_H

/* function declarations */
void init_jwsPagStaticConfig(void);
Netsnmp_Node_Handler handle_jwsPagStaticLoadBalance;
Netsnmp_Node_Handler handle_jwsPagChannelNumber;

#endif /* JWSPAGSTATICCONFIG_H */
