/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17821 2009-11-11 09:00:00Z dts12 $
 */
#ifndef JWSPORTBASEDVLANTABLE_H
#define JWSPORTBASEDVLANTABLE_H

/* function declarations */
void init_jwsPortbasedVlanTable(void);
void initialize_table_jwsPortbasedVlanTable(void);
Netsnmp_Node_Handler jwsPortbasedVlanTable_handler;
Netsnmp_First_Data_Point  jwsPortbasedVlanTable_get_first_data_point;
Netsnmp_Next_Data_Point   jwsPortbasedVlanTable_get_next_data_point;

/* column number definitions for table jwsPortbasedVlanTable */
       #define COLUMN_JWSPORTBASEDVLANPORTINDEX		1
       #define COLUMN_JWSPORTBASEDVLANSWITCHPORTS		2
#endif /* JWSPORTBASEDVLANTABLE_H */
