/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17821 2009-11-11 09:00:00Z dts12 $
 */
#ifndef JWSPAGSTATICTABLE_H
#define JWSPAGSTATICTABLE_H

/* function declarations */
void init_jwsPagStaticTable(void);
void initialize_table_jwsPagStaticTable(void);
Netsnmp_Node_Handler jwsPagStaticTable_handler;
Netsnmp_First_Data_Point  jwsPagStaticTable_get_first_data_point;
Netsnmp_Next_Data_Point   jwsPagStaticTable_get_next_data_point;

/* column number definitions for table jwsPagStaticTable */
       #define COLUMN_JWSPAGCHANNELINDEX		1
       #define COLUMN_JWSPAGCHANNELTRUNKID		2
       #define COLUMN_JWSPAGCHANNELMEMBERS		3
       #define COLUMN_JWSPAGCHANNELROWSTATUS		4
#endif /* JWSPAGSTATICTABLE_H */
