/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17821 2009-11-11 09:00:00Z dts12 $
 */
#ifndef JWSQOSCONFIGGROUP_H
#define JWSQOSCONFIGGROUP_H

/* function declarations */
void init_jwsQosConfigGroup(void);
void initialize_table_jwsQosPortConfigTable(void);
Netsnmp_Node_Handler jwsQosPortConfigTable_handler;
Netsnmp_First_Data_Point  jwsQosPortConfigTable_get_first_data_point;
Netsnmp_Next_Data_Point   jwsQosPortConfigTable_get_next_data_point;
void initialize_table_jwsQosPriority8021pTable(void);
Netsnmp_Node_Handler jwsQosPriority8021pTable_handler;
Netsnmp_First_Data_Point  jwsQosPriority8021pTable_get_first_data_point;
Netsnmp_Next_Data_Point   jwsQosPriority8021pTable_get_next_data_point;
void initialize_table_jwsQosPriorityDscpTable(void);
Netsnmp_Node_Handler jwsQosPriorityDscpTable_handler;
Netsnmp_First_Data_Point  jwsQosPriorityDscpTable_get_first_data_point;
Netsnmp_Next_Data_Point   jwsQosPriorityDscpTable_get_next_data_point;

/* column number definitions for table jwsQosPortConfigTable */
       #define COLUMN_JWSQOSPORTINDEX		1
       #define COLUMN_JWSQOSPORTPRIOASSIGNMODE		2
       #define COLUMN_JWSQOSPORTPRIOMAPRULE		3
       #define COLUMN_JWSQOSPORTDEFAULTPRIOLEVEL		4
       #define COLUMN_JWSQOSPORTSCHEDULINGMODE		5

/* column number definitions for table jwsQosPriority8021pTable */
       #define COLUMN_JWSQOS8021PPRIORITYINDEX		1
       #define COLUMN_JWSQOS8021PPRIORITYQUEUEID		2

/* column number definitions for table jwsQosPriorityDscpTable */
       #define COLUMN_JWSQOSDSCPPRIORITYINDEX		1
       #define COLUMN_JWSQOSDSCPPRIORITYQUEUEID		2
#endif /* JWSQOSCONFIGGROUP_H */
