/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef JWSRSTPGROUP_H
#define JWSRSTPGROUP_H

/* function declarations */
void init_jwsRstpGroup(void);
Netsnmp_Node_Handler handle_jwsStpAdminStatus;
Netsnmp_Node_Handler handle_jwsStpPriority;
Netsnmp_Node_Handler handle_jwsStpMaxAge;
Netsnmp_Node_Handler handle_jwsStpHelloTime;
Netsnmp_Node_Handler handle_jwsStpForwardDelay;

#endif /* JWSRSTPGROUP_H */
