/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17821 2009-11-11 09:00:00Z dts12 $
 */
#ifndef JWSSTPPORTTABLE_H
#define JWSSTPPORTTABLE_H

/* function declarations */
void init_jwsStpPortTable(void);
void initialize_table_jwsStpPortTable(void);
Netsnmp_Node_Handler jwsStpPortTable_handler;
Netsnmp_First_Data_Point  jwsStpPortTable_get_first_data_point;
Netsnmp_Next_Data_Point   jwsStpPortTable_get_next_data_point;

/* column number definitions for table jwsStpPortTable */
       #define COLUMN_JWSSTPPORT		1
       #define COLUMN_JWSSTPPORTENABLE		2
       #define COLUMN_JWSSTPPORTPRIORITY		3
       #define COLUMN_JWSSTPPORTPATHCOST		4
       #define COLUMN_JWSSTPPORTPATHCOSTAUTOCALCULATE		5
#endif /* JWSSTPPORTTABLE_H */
