/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef JWSSTATICMCASTGROUP_H
#define JWSSTATICMCASTGROUP_H

/* function declarations */
void init_jwsStaticMcastGroup(void);
Netsnmp_Node_Handler handle_jwsStaticMcastEnableStatus;
Netsnmp_Node_Handler handle_jwsStaticMcastNumber;

#endif /* JWSSTATICMCASTGROUP_H */
