/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17821 2009-11-11 09:00:00Z dts12 $
 */
#ifndef JWSTRAPCONFIGGROUP_H
#define JWSTRAPCONFIGGROUP_H

/* function declarations */
void init_jwsTrapConfigGroup(void);
Netsnmp_Node_Handler handle_jwsTrapPowerSupplyEnableValue;
void initialize_table_jwsTrapPortConfigTable(void);
Netsnmp_Node_Handler jwsTrapPortConfigTable_handler;
Netsnmp_First_Data_Point  jwsTrapPortConfigTable_get_first_data_point;
Netsnmp_Next_Data_Point   jwsTrapPortConfigTable_get_next_data_point;
void initialize_table_jwsTrapRingConfigTable(void);
Netsnmp_Node_Handler jwsTrapRingConfigTable_handler;
Netsnmp_First_Data_Point  jwsTrapRingConfigTable_get_first_data_point;
Netsnmp_Next_Data_Point   jwsTrapRingConfigTable_get_next_data_point;

/* column number definitions for table jwsTrapPortConfigTable */
       #define COLUMN_JWSTRAPPORTID		1
       #define COLUMN_JWSTRAPPORTSTATUSENABLEVALUE		2
       #define COLUMN_JWSTRAPPORTTXTHRESHOLDENABLEVALUE		3
       #define COLUMN_JWSTRAPPORTTXTHRESHOLDPERCENTAGE		4
       #define COLUMN_JWSTRAPPORTRXTHRESHOLDENABLEVALUE		5
       #define COLUMN_JWSTRAPPORTRXTHRESHOLDPERCENTAGE		6

/* column number definitions for table jwsTrapRingConfigTable */
       #define COLUMN_JWSTRAPRINGID		1
       #define COLUMN_JWSTRAPRINGSTATUSENABLEVALUE		2
#endif /* JWSTRAPCONFIGGROUP_H */
