/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.notify.conf 10110 2004-04-15 12:29:19Z dts12 $
 */
#ifndef JWSTRAPPOWERSUPPLY_H
#define JWSTRAPPOWERSUPPLY_H

/* function declarations */
void init_jwsTrapPowerSupply(void);
SNMPAlarmCallback send_jwsTrapPowerSupply_notification;
SNMPAlarmCallback send_jwsTrapPowerSupply_alarm_led;

#endif /* JWSTRAPPOWERSUPPLY_H */
