/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.notify.conf 10110 2004-04-15 12:29:19Z dts12 $
 */
#ifndef JWSTRAPPOWERCHANNELSTATUS_H
#define JWSTRAPPOWERCHANNELSTATUS_H

/* function declarations */
void init_jwsTrapPowerChannelStatus(void);
SNMPAlarmCallback send_jwsTrapPowerChannelStatus_notification;

#endif /* JWSTRAPPOWERCHANNELSTATUS_H */
