/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.notify.conf 10110 2004-04-15 12:29:19Z dts12 $
 */
#ifndef JWSTRAPPORTRATETHRESHOLD_H
#define JWSTRAPPORTRATETHRESHOLD_H

enum direc{
    UPSTREAM = 1,
    DOWNSTREAM = 2,
};

struct trap_msg
{
    int port_id;
    enum direc direction;
    int percentage;
};

/* function declarations */
void init_jwsTrapPortRateThreshold(void);
SNMPAlarmCallback send_jwsPortRateThreshold_notification;

int send_jwsTrapPortRateThreshold_trap( struct trap_msg *msg );

#endif /* JWSTRAPPORTRATETHRESHOLD_H */
