/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef JWSTRAPPORTSTATUS_H
#define JWSTRAPPORTSTATUS_H

/* function declarations */
void init_jwsTrapPortStatus(void);
SNMPAlarmCallback send_jwsTrapPortStatus_notification;

#endif /* JWSTRAPPORTSTATUS_H */
