/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef JWSVLANMNGTGROUP_H
#define JWSVLANMNGTGROUP_H

/* function declarations */
void init_jwsVlanMngtGroup(void);
Netsnmp_Node_Handler handle_jwsVlanMode;
Netsnmp_Node_Handler handle_jwsDot1qVlanNumber;

#endif /* JWSVLANMNGTGROUP_H */
