/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17821 2009-11-11 09:00:00Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "jwsDot1qVlanStaticTable.h"

#include "jws_ubus_if.h"
#include "stdlib.h"
#include "jws_convert.h"
#include "jwslog.h"

/* create a new row in the (unsorted) table */
struct jwsDot1qVlanStaticTable_entry *
jwsDot1qVlanStaticTable_createEntry(
                 long  jwsDot1qVlanIndex,
                 struct jwsDot1qVlanStaticTable_entry *table_entry
                );
int jwsDot1qVlanStaticTable_load(netsnmp_cache *cache, void *magic);
void jwsDot1qVlanStaticTable_free(netsnmp_cache *cache, void *magic);
void jwsDot1qVlanStaticTable_removeTable();
/* remove a row from the table */
void
jwsDot1qVlanStaticTable_removeEntry( struct jwsDot1qVlanStaticTable_entry *entry );

/** Initializes the jwsDot1qVlanStaticTable module */
void
init_jwsDot1qVlanStaticTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_jwsDot1qVlanStaticTable();
}

//  # Determine the first/last column names

/** Initialize the jwsDot1qVlanStaticTable table by defining its contents and how it's structured */
void
initialize_table_jwsDot1qVlanStaticTable(void)
{
    static oid jwsDot1qVlanStaticTable_oid[] = {1,3,6,1,4,1,33444,2,2,9,1,4};
    size_t jwsDot1qVlanStaticTable_oid_len   = OID_LENGTH(jwsDot1qVlanStaticTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    reg = netsnmp_create_handler_registration(
              "jwsDot1qVlanStaticTable",     jwsDot1qVlanStaticTable_handler,
              jwsDot1qVlanStaticTable_oid, jwsDot1qVlanStaticTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: jwsDot1qVlanIndex */
                           0);
    table_info->min_column = COLUMN_JWSDOT1QVLANINDEX;
    table_info->max_column = COLUMN_JWSDOT1QVLANROWSTATUS;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = jwsDot1qVlanStaticTable_get_first_data_point;
    iinfo->get_next_data_point  = jwsDot1qVlanStaticTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
    netsnmp_inject_handler( reg,
            netsnmp_get_cache_handler(1,
                    jwsDot1qVlanStaticTable_load, jwsDot1qVlanStaticTable_free,
                    jwsDot1qVlanStaticTable_oid, jwsDot1qVlanStaticTable_oid_len));
}

    /* Typical data structure for a row entry */
struct jwsDot1qVlanStaticTable_entry {
    /* Index values */
    //long jwsDot1qVlanIndex;

    /* Column values */
    long jwsDot1qVlanIndex;
    long old_jwsDot1qVlanIndex;
    u_long jwsDot1qVlanId;
    u_long old_jwsDot1qVlanId;
#define DOT1Q_VLAN_NAME_LEN   (16)
    char jwsDot1qVlanName[DOT1Q_VLAN_NAME_LEN];
    size_t jwsDot1qVlanName_len;
    char old_jwsDot1qVlanName[DOT1Q_VLAN_NAME_LEN];
    size_t old_jwsDot1qVlanName_len;
#define DOT1Q_VLAN_PORTS_LIST_LEN (8)
    char jwsDot1qVlanEgressPorts[DOT1Q_VLAN_PORTS_LIST_LEN];
    size_t jwsDot1qVlanEgressPorts_len;
    char old_jwsDot1qVlanEgressPorts[DOT1Q_VLAN_PORTS_LIST_LEN];
    size_t old_jwsDot1qVlanEgressPorts_len;
    char jwsDot1qVlanTaggedPorts[DOT1Q_VLAN_PORTS_LIST_LEN];
    size_t jwsDot1qVlanTaggedPorts_len;
    char old_jwsDot1qVlanTaggedPorts[DOT1Q_VLAN_PORTS_LIST_LEN];
    size_t old_jwsDot1qVlanTaggedPorts_len;
    long jwsDot1qVlanRowStatus;

    /* Illustrate using a simple linked list */
    int   valid;
    struct jwsDot1qVlanStaticTable_entry *next;
};

struct jwsDot1qVlanStaticTable_entry  *jwsDot1qVlanStaticTable_head;

int jwsDot1qVlanStaticTable_load(netsnmp_cache *cache, void *magic)
{
    int ret;
    int i, dot1q_vlan_num;
    struct jwsDot1qVlanStaticTable_entry table_entry;

    ret = ubus_invoke_command("vlan_config", "vlan_config_get", get_ret_handler_cb, 
                                "{\"get_args\":[\"dot1q_vlan_num\"]}");
    if (ret != 0)
    {
        LogWrite(ERROR, "file:%s line:%d func:%s, invoke get_args dot1q_vlan_num failed\n",
                        __FILENAME__, __LINE__, __FUNCTION__);
        return -1;
    }
    dot1q_vlan_num = atoi(jws_read_buf_str());
    if (dot1q_vlan_num == -1)
    {
        LogWrite(ERROR, "file:%s line:%d func:%s, 802.1Q vlan disable\n",
                        __FILENAME__, __LINE__, __FUNCTION__);
        return -1;
    }

    jwsDot1qVlanStaticTable_removeTable();

    for (i = 1; i <= dot1q_vlan_num; i++) {
        table_entry.jwsDot1qVlanRowStatus = 1;
        jwsDot1qVlanStaticTable_createEntry(i, &table_entry);
    }

    return 0;
}

void jwsDot1qVlanStaticTable_free(netsnmp_cache *cache, void *magic)
{
    jwsDot1qVlanStaticTable_removeTable();
}

/* remove a table */
void jwsDot1qVlanStaticTable_removeTable( ) {

    struct jwsDot1qVlanStaticTable_entry *ptr;

    LogWrite(DEBUG, "file:%s line:%d func:%s, remove table\n",
                        __FILENAME__, __LINE__, __FUNCTION__);
    for ( ptr  = jwsDot1qVlanStaticTable_head; ptr != NULL; ptr = ptr->next ) {
        jwsDot1qVlanStaticTable_removeEntry( ptr );
    }

}

/* create a new row in the (unsorted) table */
struct jwsDot1qVlanStaticTable_entry *
jwsDot1qVlanStaticTable_createEntry(
                 long  jwsDot1qVlanIndex,
                 struct jwsDot1qVlanStaticTable_entry *table_entry
                ) {
    struct jwsDot1qVlanStaticTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct jwsDot1qVlanStaticTable_entry);
    if (!entry)
        return NULL;

    entry->jwsDot1qVlanIndex = jwsDot1qVlanIndex;

    if (NULL != table_entry){
        entry->jwsDot1qVlanRowStatus = table_entry->jwsDot1qVlanRowStatus;
    }

    entry->next = jwsDot1qVlanStaticTable_head;
    jwsDot1qVlanStaticTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
jwsDot1qVlanStaticTable_removeEntry( struct jwsDot1qVlanStaticTable_entry *entry ) {
    struct jwsDot1qVlanStaticTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = jwsDot1qVlanStaticTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        jwsDot1qVlanStaticTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
jwsDot1qVlanStaticTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = jwsDot1qVlanStaticTable_head;
    return jwsDot1qVlanStaticTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
jwsDot1qVlanStaticTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct jwsDot1qVlanStaticTable_entry *entry = (struct jwsDot1qVlanStaticTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->jwsDot1qVlanIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the jwsDot1qVlanStaticTable table */
int
jwsDot1qVlanStaticTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct jwsDot1qVlanStaticTable_entry          *table_entry;

    struct jwsDot1qVlanStaticTable_entry          *table_row = NULL;
    int ret;
    char str[100] = {0};
    char value[50];
    unsigned int data;

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsDot1qVlanStaticTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            bzero(str, sizeof(str));
    
            switch (table_info->colnum) {
            case COLUMN_JWSDOT1QVLANINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsDot1qVlanIndex);
                break;
            case COLUMN_JWSDOT1QVLANID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_cmd_enc(str, sizeof(str), table_entry->jwsDot1qVlanIndex, "dot1q_vlan_id");
                ret = ubus_invoke_command("vlan_config", "vlan_config_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsDot1qVlanId = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->jwsDot1qVlanId);
                break;
            case COLUMN_JWSDOT1QVLANNAME:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_cmd_enc(str, sizeof(str), table_entry->jwsDot1qVlanIndex, 
                                "dot1q_vlan_name");
                ret = ubus_invoke_command("vlan_config", "vlan_config_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                table_entry->jwsDot1qVlanName_len = strlen(jws_read_buf_str());
                strcpy(table_entry->jwsDot1qVlanName, jws_read_buf_str());

                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->jwsDot1qVlanName,
                                          table_entry->jwsDot1qVlanName_len);
                break;
            case COLUMN_JWSDOT1QVLANEGRESSPORTS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_cmd_enc(str, sizeof(str), table_entry->jwsDot1qVlanIndex, 
                                "dot1q_vlan_portlist");
                ret = ubus_invoke_command("vlan_config", "vlan_config_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                table_entry->jwsDot1qVlanEgressPorts_len = count_char(jws_read_buf_str(), '-') + 1;
                convert_str2array(jws_read_buf_str(), 
                    table_entry->jwsDot1qVlanEgressPorts, table_entry->jwsDot1qVlanEgressPorts_len);

                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->jwsDot1qVlanEgressPorts,
                                          table_entry->jwsDot1qVlanEgressPorts_len);
                break;
            case COLUMN_JWSDOT1QVLANTAGGEDPORTS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_cmd_enc(str, sizeof(str), table_entry->jwsDot1qVlanIndex, 
                                "dot1q_vlan_taglist");
                ret = ubus_invoke_command("vlan_config", "vlan_config_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                table_entry->jwsDot1qVlanTaggedPorts_len = count_char(jws_read_buf_str(), '-') + 1;
                convert_str2array(jws_read_buf_str(), 
                    table_entry->jwsDot1qVlanTaggedPorts, table_entry->jwsDot1qVlanTaggedPorts_len);

                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->jwsDot1qVlanTaggedPorts,
                                          table_entry->jwsDot1qVlanTaggedPorts_len);
                break;
            case COLUMN_JWSDOT1QVLANROWSTATUS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsDot1qVlanRowStatus);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsDot1qVlanStaticTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSDOT1QVLANINDEX:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSDOT1QVLANID:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_uint( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSDOT1QVLANNAME:
	        /* or possiblc 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->jwsDot1qVlanName));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSDOT1QVLANEGRESSPORTS:
	        /* or possiblc 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->jwsDot1qVlanEgressPorts));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSDOT1QVLANTAGGEDPORTS:
	        /* or possiblc 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->jwsDot1qVlanTaggedPorts));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSDOT1QVLANROWSTATUS:
                ret = netsnmp_check_vb_rowstatus(request->requestvb,
                         (table_entry ? RS_ACTIVE : RS_NONEXISTENT ));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsDot1qVlanStaticTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            bzero(str, sizeof(str));
    
            switch (table_info->colnum) {
            case COLUMN_JWSDOT1QVLANROWSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_CREATEANDGO:
                case RS_CREATEANDWAIT:
                    table_row = jwsDot1qVlanStaticTable_createEntry(
                        *table_info->indexes->val.integer,
                        NULL
                        );

                    snprintf(value, sizeof(value), "%ld", *table_info->indexes->val.integer);
                    #if 0
                    ubus_set_cmd_enc(str, sizeof(str), *table_info->indexes->val.integer, 
                                    "dot1q_vlan_id", value);
                    ret = ubus_invoke_command("vlan_config", "vlan_config_set", 
                                            set_ret_handler_cb, str);
                    #endif
                                            
                    ubus_add_cmd_enc(str, sizeof(str), *table_info->indexes->val.integer);
                    ret = ubus_invoke_command("vlan_config", "vlan_config_set", 
                                            set_ret_handler_cb, str);
                    if (ret != 0) {
                        return SNMP_ERR_NOSUCHNAME;
                    }

                    if (table_row) {
                        netsnmp_insert_iterator_context( request, table_row );
                    } else {
                        netsnmp_set_request_error( reqinfo, request,
                                                   SNMP_ERR_RESOURCEUNAVAILABLE );
                        return SNMP_ERR_NOERROR;
                    }
                }
            }
        }
        break;

    case MODE_SET_FREE:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsDot1qVlanStaticTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSDOT1QVLANROWSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_CREATEANDGO:
                case RS_CREATEANDWAIT:
                    if (table_entry && !table_entry->valid) {
                        jwsDot1qVlanStaticTable_removeEntry( table_row );
                    }
                }
            }
        }
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsDot1qVlanStaticTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            bzero(str, sizeof(str));
    
            switch (table_info->colnum) {
            case COLUMN_JWSDOT1QVLANINDEX:
                table_entry->old_jwsDot1qVlanIndex = table_entry->jwsDot1qVlanIndex;
                table_entry->jwsDot1qVlanIndex     = *request->requestvb->val.integer;
                break;
            case COLUMN_JWSDOT1QVLANID:
                table_entry->old_jwsDot1qVlanId = table_entry->jwsDot1qVlanId;
                table_entry->jwsDot1qVlanId     = *request->requestvb->val.integer;

                snprintf(value, sizeof(value), "%ld", table_entry->jwsDot1qVlanId);
                ubus_set_cmd_enc(str, sizeof(str), table_entry->jwsDot1qVlanIndex, 
                                "dot1q_vlan_id", value);
                ret = ubus_invoke_command("vlan_config", "vlan_config_set", 
                                        set_ret_handler_cb, str);
                if (ret != 0) {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSDOT1QVLANNAME:
                memcpy( table_entry->old_jwsDot1qVlanName,
                        table_entry->jwsDot1qVlanName,
                        sizeof(table_entry->jwsDot1qVlanName));
                table_entry->old_jwsDot1qVlanName_len =
                        table_entry->jwsDot1qVlanName_len;
                memset( table_entry->jwsDot1qVlanName, 0,
                        sizeof(table_entry->jwsDot1qVlanName));
                memcpy( table_entry->jwsDot1qVlanName,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->jwsDot1qVlanName_len =
                        request->requestvb->val_len;

                ubus_set_cmd_enc(str, sizeof(str), table_entry->jwsDot1qVlanIndex, 
                                "dot1q_vlan_name", table_entry->jwsDot1qVlanName);
                ret = ubus_invoke_command("vlan_config", "vlan_config_set", 
                                        set_ret_handler_cb, str);
                if (ret != 0) {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSDOT1QVLANEGRESSPORTS:
                memcpy( table_entry->old_jwsDot1qVlanEgressPorts,
                        table_entry->jwsDot1qVlanEgressPorts,
                        sizeof(table_entry->jwsDot1qVlanEgressPorts));
                table_entry->old_jwsDot1qVlanEgressPorts_len =
                        table_entry->jwsDot1qVlanEgressPorts_len;
                memset( table_entry->jwsDot1qVlanEgressPorts, 0,
                        sizeof(table_entry->jwsDot1qVlanEgressPorts));
                memcpy( table_entry->jwsDot1qVlanEgressPorts,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->jwsDot1qVlanEgressPorts_len =
                        request->requestvb->val_len;

                convert_array2str(table_entry->jwsDot1qVlanEgressPorts, 
                    table_entry->jwsDot1qVlanEgressPorts_len, value, 
                    3*table_entry->jwsDot1qVlanEgressPorts_len);
                ubus_set_cmd_enc(str, sizeof(str), table_entry->jwsDot1qVlanIndex, 
                                "dot1q_vlan_portlist", value);
                ret = ubus_invoke_command("vlan_config", "vlan_config_set", 
                                        set_ret_handler_cb, str);
                if (ret != 0) {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSDOT1QVLANTAGGEDPORTS:
                memcpy( table_entry->old_jwsDot1qVlanTaggedPorts,
                        table_entry->jwsDot1qVlanTaggedPorts,
                        sizeof(table_entry->jwsDot1qVlanTaggedPorts));
                table_entry->old_jwsDot1qVlanTaggedPorts_len =
                        table_entry->jwsDot1qVlanTaggedPorts_len;
                memset( table_entry->jwsDot1qVlanTaggedPorts, 0,
                        sizeof(table_entry->jwsDot1qVlanTaggedPorts));
                memcpy( table_entry->jwsDot1qVlanTaggedPorts,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->jwsDot1qVlanTaggedPorts_len =
                        request->requestvb->val_len;

                convert_array2str(table_entry->jwsDot1qVlanTaggedPorts, 
                    table_entry->jwsDot1qVlanTaggedPorts_len, value, 
                    3*table_entry->jwsDot1qVlanTaggedPorts_len);
                ubus_set_cmd_enc(str, sizeof(str), table_entry->jwsDot1qVlanIndex, 
                                "dot1q_vlan_taglist", value);
                ret = ubus_invoke_command("vlan_config", "vlan_config_set", 
                                        set_ret_handler_cb, str);
                if (ret != 0) {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            }
        }
        /* Check the internal consistency of an active row */
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsDot1qVlanStaticTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSDOT1QVLANROWSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_ACTIVE:
                case RS_CREATEANDGO:
                    if (0/* XXX */) {
                        netsnmp_set_request_error( reqinfo, request,
                                                   SNMP_ERR_INCONSISTENTVALUE );
                        return SNMP_ERR_NOERROR;
                    }
                }
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsDot1qVlanStaticTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSDOT1QVLANINDEX:
                table_entry->jwsDot1qVlanIndex     = table_entry->old_jwsDot1qVlanIndex;
                table_entry->old_jwsDot1qVlanIndex = 0;
                break;
            case COLUMN_JWSDOT1QVLANID:
                table_entry->jwsDot1qVlanId     = table_entry->old_jwsDot1qVlanId;
                table_entry->old_jwsDot1qVlanId = 0;
                break;
            case COLUMN_JWSDOT1QVLANNAME:
                memcpy( table_entry->jwsDot1qVlanName,
                        table_entry->old_jwsDot1qVlanName,
                        sizeof(table_entry->jwsDot1qVlanName));
                memset( table_entry->old_jwsDot1qVlanName, 0,
                        sizeof(table_entry->jwsDot1qVlanName));
                table_entry->jwsDot1qVlanName_len =
                        table_entry->old_jwsDot1qVlanName_len;
                break;
            case COLUMN_JWSDOT1QVLANEGRESSPORTS:
                memcpy( table_entry->jwsDot1qVlanEgressPorts,
                        table_entry->old_jwsDot1qVlanEgressPorts,
                        sizeof(table_entry->jwsDot1qVlanEgressPorts));
                memset( table_entry->old_jwsDot1qVlanEgressPorts, 0,
                        sizeof(table_entry->jwsDot1qVlanEgressPorts));
                table_entry->jwsDot1qVlanEgressPorts_len =
                        table_entry->old_jwsDot1qVlanEgressPorts_len;
                break;
            case COLUMN_JWSDOT1QVLANTAGGEDPORTS:
                memcpy( table_entry->jwsDot1qVlanTaggedPorts,
                        table_entry->old_jwsDot1qVlanTaggedPorts,
                        sizeof(table_entry->jwsDot1qVlanTaggedPorts));
                memset( table_entry->old_jwsDot1qVlanTaggedPorts, 0,
                        sizeof(table_entry->jwsDot1qVlanTaggedPorts));
                table_entry->jwsDot1qVlanTaggedPorts_len =
                        table_entry->old_jwsDot1qVlanTaggedPorts_len;
                break;
            case COLUMN_JWSDOT1QVLANROWSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_CREATEANDGO:
                case RS_CREATEANDWAIT:
                    if (table_entry && !table_entry->valid) {
                        jwsDot1qVlanStaticTable_removeEntry( table_row );
                    }
                }
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsDot1qVlanStaticTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSDOT1QVLANROWSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_CREATEANDGO:
                    table_entry->valid = 1;
                    /* Fall-through */
                case RS_ACTIVE:
                    table_entry->jwsDot1qVlanRowStatus = RS_ACTIVE;
                    break;

                case RS_CREATEANDWAIT:
                    table_entry->valid = 1;
                    /* Fall-through */
                case RS_NOTINSERVICE:
                    table_entry->jwsDot1qVlanRowStatus = RS_NOTINSERVICE;
                    break;

                case RS_DESTROY:

                    ubus_clear_cmd_enc(str, sizeof(str), *table_info->indexes->val.integer);
                    ret = ubus_invoke_command("vlan_config", "vlan_config_clear", 
                                            clear_ret_handler_cb, str);
                    if (ret != 0) {
                        return SNMP_ERR_NOSUCHNAME;
                    }

                    //jwsDot1qVlanStaticTable_removeEntry( table_row );
                }
            }
        }
        break;
    }
    return SNMP_ERR_NOERROR;
}
