/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "jwsDevSnmpConfig.h"

#include "jws_ubus_if.h"
#include <arpa/inet.h>
#include <stdio.h>
#include <stdlib.h>

/** Initializes the jwsDevSnmpConfig module */
void
init_jwsDevSnmpConfig(void)
{
    static oid jwsSnmpEnable_oid[] = { 1,3,6,1,4,1,33444,2,2,1,4,1 };
    static oid jwsSnmpReadOnlyCommunity_oid[] = { 1,3,6,1,4,1,33444,2,2,1,4,2 };
    static oid jwsSnmpReadWriteCommunity_oid[] = { 1,3,6,1,4,1,33444,2,2,1,4,3 };
    static oid jwsSnmpPort_oid[] = { 1,3,6,1,4,1,33444,2,2,1,4,4 };
    static oid jwsSnmpTrapEnable_oid[] = { 1,3,6,1,4,1,33444,2,2,1,4,5 };
    static oid jwsSnmpTrapPort_oid[] = { 1,3,6,1,4,1,33444,2,2,1,4,6 };
    static oid jwsSnmpTrapServerIP_oid[] = { 1,3,6,1,4,1,33444,2,2,1,4,7 };

  DEBUGMSGTL(("jwsDevSnmpConfig", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("jwsSnmpEnable", handle_jwsSnmpEnable,
                               jwsSnmpEnable_oid, OID_LENGTH(jwsSnmpEnable_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("jwsSnmpReadOnlyCommunity", handle_jwsSnmpReadOnlyCommunity,
                               jwsSnmpReadOnlyCommunity_oid, OID_LENGTH(jwsSnmpReadOnlyCommunity_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("jwsSnmpReadWriteCommunity", handle_jwsSnmpReadWriteCommunity,
                               jwsSnmpReadWriteCommunity_oid, OID_LENGTH(jwsSnmpReadWriteCommunity_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("jwsSnmpPort", handle_jwsSnmpPort,
                               jwsSnmpPort_oid, OID_LENGTH(jwsSnmpPort_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("jwsSnmpTrapEnable", handle_jwsSnmpTrapEnable,
                               jwsSnmpTrapEnable_oid, OID_LENGTH(jwsSnmpTrapEnable_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("jwsSnmpTrapPort", handle_jwsSnmpTrapPort,
                               jwsSnmpTrapPort_oid, OID_LENGTH(jwsSnmpTrapPort_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("jwsSnmpTrapServerIP", handle_jwsSnmpTrapServerIP,
                               jwsSnmpTrapServerIP_oid, OID_LENGTH(jwsSnmpTrapServerIP_oid),
                               HANDLER_CAN_RWRITE
        ));
}

int
handle_jwsSnmpEnable(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    int data = 0;
    char str[100] = {0};
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:

            ret = ubus_invoke_command("snmp", "snmp_get", get_ret_handler_cb, 
                                "{\"get_args\":[\"status\"]}");
            if (ret != 0)
            {
                return SNMP_ERR_NOSUCHNAME;
            }
            data = atoi(jws_read_buf_str());

            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     (u_char *) &data,
                                     sizeof(data));

            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        case MODE_SET_RESERVE1:
                /* or you could use netsnmp_check_vb_type_and_size instead */
            ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
            if ( ret != SNMP_ERR_NOERROR ) {
                netsnmp_set_request_error(reqinfo, requests, ret );
            }
            break;

        case MODE_SET_RESERVE2:
            /* XXX malloc "undo" storage buffer */
            if (0/* XXX if malloc, or whatever, failed: */) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_RESOURCEUNAVAILABLE);
            }
            break;

        case MODE_SET_FREE:
            /* XXX: free resources allocated in RESERVE1 and/or
               RESERVE2.  Something failed somewhere, and the states
               below won't be called. */
            break;

        case MODE_SET_ACTION:
            data = *requests->requestvb->val.integer;
            snprintf(str, sizeof(str), "{\"set_args\":[{\"status\":\"%d\"}]}", data);
            ret = ubus_invoke_command("snmp", "snmp_set", set_ret_handler_cb, str);
            if (ret != 0)
            {
                    return SNMP_ERR_NOSUCHNAME;
            }
            /* XXX: perform the value change here */
            if (0/* XXX: error? */) {
                //netsnmp_set_request_error(reqinfo, requests, /* some error */);
            }
            break;

        case MODE_SET_COMMIT:
            /* XXX: delete temporary storage */
            if (0/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_COMMITFAILED);
            }
            break;

        case MODE_SET_UNDO:
            /* XXX: UNDO and return to previous value for the object */
            if (0/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_UNDOFAILED);
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_jwsSnmpEnable\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_jwsSnmpReadOnlyCommunity(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    char str[256];
    char value[65];
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            ret = ubus_invoke_command("snmp", "snmp_get", get_ret_handler_cb, 
                                "{\"get_args\":[\"readonly_name\"]}");
            if (ret != 0) {
                return SNMP_ERR_NOSUCHNAME;
            }

            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     (u_char *) jws_read_buf_str(),
                                     strlen(jws_read_buf_str()));
            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        case MODE_SET_RESERVE1:
                /* or you could use netsnmp_check_vb_type_and_size instead */
            ret = netsnmp_check_vb_type(requests->requestvb, ASN_OCTET_STR);
            if ( ret != SNMP_ERR_NOERROR ) {
                netsnmp_set_request_error(reqinfo, requests, ret );
            }
            break;

        case MODE_SET_RESERVE2:
            /* XXX malloc "undo" storage buffer */
            if (0/* XXX if malloc, or whatever, failed: */) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_RESOURCEUNAVAILABLE);
            }
            break;

        case MODE_SET_FREE:
            /* XXX: free resources allocated in RESERVE1 and/or
               RESERVE2.  Something failed somewhere, and the states
               below won't be called. */
            break;

        case MODE_SET_ACTION:
            bzero(value, sizeof(value));
            memcpy(value,requests->requestvb->val.string,requests->requestvb->val_len);
            snprintf(str, sizeof(str), "{\"set_args\":[{\"readonly_name\":\"%s\"}]}", value);
            ret = ubus_invoke_command("snmp", "snmp_set", set_ret_handler_cb, str);
            if (ret != 0) {
                return SNMP_ERR_NOSUCHNAME;
            }
            /* XXX: perform the value change here */
            if (0/* XXX: error? */) {
                //netsnmp_set_request_error(reqinfo, requests, /* some error */);
            }
            break;

        case MODE_SET_COMMIT:
            /* XXX: delete temporary storage */
            if (0/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_COMMITFAILED);
            }
            break;

        case MODE_SET_UNDO:
            /* XXX: UNDO and return to previous value for the object */
            if (0/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_UNDOFAILED);
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_jwsSnmpReadOnlyCommunity\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_jwsSnmpReadWriteCommunity(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    char str[256];
    char value[65];
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            ret = ubus_invoke_command("snmp", "snmp_get", get_ret_handler_cb, 
                                "{\"get_args\":[\"readwrite_name\"]}");
            if (ret != 0) {
                return SNMP_ERR_NOSUCHNAME;
            }

            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     (u_char *) jws_read_buf_str(),
                                     strlen(jws_read_buf_str()));
            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        case MODE_SET_RESERVE1:
                /* or you could use netsnmp_check_vb_type_and_size instead */
            ret = netsnmp_check_vb_type(requests->requestvb, ASN_OCTET_STR);
            if ( ret != SNMP_ERR_NOERROR ) {
                netsnmp_set_request_error(reqinfo, requests, ret );
            }
            break;

        case MODE_SET_RESERVE2:
            /* XXX malloc "undo" storage buffer */
            if (0/* XXX if malloc, or whatever, failed: */) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_RESOURCEUNAVAILABLE);
            }
            break;

        case MODE_SET_FREE:
            /* XXX: free resources allocated in RESERVE1 and/or
               RESERVE2.  Something failed somewhere, and the states
               below won't be called. */
            break;

        case MODE_SET_ACTION:
            bzero(value, sizeof(value));
            memcpy(value,requests->requestvb->val.string,requests->requestvb->val_len);
            snprintf(str, sizeof(str), "{\"set_args\":[{\"readwrite_name\":\"%s\"}]}", value);
            ret = ubus_invoke_command("snmp", "snmp_set", set_ret_handler_cb, str);
            if (ret != 0) {
                return SNMP_ERR_NOSUCHNAME;
            }
            /* XXX: perform the value change here */
            if (0/* XXX: error? */) {
                //netsnmp_set_request_error(reqinfo, requests, /* some error */);
            }
            break;

        case MODE_SET_COMMIT:
            /* XXX: delete temporary storage */
            if (0/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_COMMITFAILED);
            }
            break;

        case MODE_SET_UNDO:
            /* XXX: UNDO and return to previous value for the object */
            if (0/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_UNDOFAILED);
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_jwsSnmpReadWriteCommunity\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_jwsSnmpPort(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    int data = 0;
    char str[100] = {0};
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            ret = ubus_invoke_command("snmp", "snmp_get", get_ret_handler_cb, 
                                "{\"get_args\":[\"port\"]}");
            if (ret != 0)
            {
                return SNMP_ERR_NOSUCHNAME;
            }
            data = atoi(jws_read_buf_str());

            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     (u_char *) &data,
                                     sizeof(data));

            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        case MODE_SET_RESERVE1:
                /* or you could use netsnmp_check_vb_type_and_size instead */
            ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
            if ( ret != SNMP_ERR_NOERROR ) {
                netsnmp_set_request_error(reqinfo, requests, ret );
            }
            break;

        case MODE_SET_RESERVE2:
            /* XXX malloc "undo" storage buffer */
            if (0/* XXX if malloc, or whatever, failed: */) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_RESOURCEUNAVAILABLE);
            }
            break;

        case MODE_SET_FREE:
            /* XXX: free resources allocated in RESERVE1 and/or
               RESERVE2.  Something failed somewhere, and the states
               below won't be called. */
            break;

        case MODE_SET_ACTION:
            data = *requests->requestvb->val.integer;
            snprintf(str, sizeof(str), "{\"set_args\":[{\"port\":\"%d\"}]}", data);
            ret = ubus_invoke_command("snmp", "snmp_set", set_ret_handler_cb, str);
            if (ret != 0)
            {
                    return SNMP_ERR_NOSUCHNAME;
            }
            /* XXX: perform the value change here */
            if (0/* XXX: error? */) {
                //netsnmp_set_request_error(reqinfo, requests, /* some error */);
            }
            break;

        case MODE_SET_COMMIT:
            /* XXX: delete temporary storage */
            if (0/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_COMMITFAILED);
            }
            break;

        case MODE_SET_UNDO:
            /* XXX: UNDO and return to previous value for the object */
            if (0/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_UNDOFAILED);
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_jwsSnmpPort\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_jwsSnmpTrapEnable(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    int data = 0;
    char str[100] = {0};
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            ret = ubus_invoke_command("snmp", "snmp_get", get_ret_handler_cb, 
                                "{\"get_args\":[\"trap_status\"]}");
            if (ret != 0)
            {
                return SNMP_ERR_NOSUCHNAME;
            }
            data = atoi(jws_read_buf_str());

            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     (u_char *) &data,
                                     sizeof(data));
            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        case MODE_SET_RESERVE1:
                /* or you could use netsnmp_check_vb_type_and_size instead */
            ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
            if ( ret != SNMP_ERR_NOERROR ) {
                netsnmp_set_request_error(reqinfo, requests, ret );
            }
            break;

        case MODE_SET_RESERVE2:
            /* XXX malloc "undo" storage buffer */
            if (0/* XXX if malloc, or whatever, failed: */) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_RESOURCEUNAVAILABLE);
            }
            break;

        case MODE_SET_FREE:
            /* XXX: free resources allocated in RESERVE1 and/or
               RESERVE2.  Something failed somewhere, and the states
               below won't be called. */
            break;

        case MODE_SET_ACTION:
            data = *requests->requestvb->val.integer;
            snprintf(str, sizeof(str), "{\"set_args\":[{\"trap_status\":\"%d\"}]}", data);
            ret = ubus_invoke_command("snmp", "snmp_set", set_ret_handler_cb, str);
            if (ret != 0)
            {
                    return SNMP_ERR_NOSUCHNAME;
            }
            /* XXX: perform the value change here */
            if (0/* XXX: error? */) {
                //netsnmp_set_request_error(reqinfo, requests, /* some error */);
            }
            break;

        case MODE_SET_COMMIT:
            /* XXX: delete temporary storage */
            if (0/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_COMMITFAILED);
            }
            break;

        case MODE_SET_UNDO:
            /* XXX: UNDO and return to previous value for the object */
            if (0/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_UNDOFAILED);
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_jwsSnmpTrapEnable\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_jwsSnmpTrapPort(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    int data = 0;
    char str[100] = {0};
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            ret = ubus_invoke_command("snmp", "snmp_get", get_ret_handler_cb, 
                                "{\"get_args\":[\"trap_port\"]}");
            if (ret != 0)
            {
                return SNMP_ERR_NOSUCHNAME;
            }
            data = atoi(jws_read_buf_str());

            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     (u_char *) &data,
                                     sizeof(data));
            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        case MODE_SET_RESERVE1:
                /* or you could use netsnmp_check_vb_type_and_size instead */
            ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
            if ( ret != SNMP_ERR_NOERROR ) {
                netsnmp_set_request_error(reqinfo, requests, ret );
            }
            break;

        case MODE_SET_RESERVE2:
            /* XXX malloc "undo" storage buffer */
            if (0/* XXX if malloc, or whatever, failed: */) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_RESOURCEUNAVAILABLE);
            }
            break;

        case MODE_SET_FREE:
            /* XXX: free resources allocated in RESERVE1 and/or
               RESERVE2.  Something failed somewhere, and the states
               below won't be called. */
            break;

        case MODE_SET_ACTION:
            data = *requests->requestvb->val.integer;
            snprintf(str, sizeof(str), "{\"set_args\":[{\"trap_port\":\"%d\"}]}", data);
            ret = ubus_invoke_command("snmp", "snmp_set", set_ret_handler_cb, str);
            if (ret != 0)
            {
                    return SNMP_ERR_NOSUCHNAME;
            }
            /* XXX: perform the value change here */
            if (0/* XXX: error? */) {
                //netsnmp_set_request_error(reqinfo, requests, /* some error */);
            }
            break;

        case MODE_SET_COMMIT:
            /* XXX: delete temporary storage */
            if (0/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_COMMITFAILED);
            }
            break;

        case MODE_SET_UNDO:
            /* XXX: UNDO and return to previous value for the object */
            if (0/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_UNDOFAILED);
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_jwsSnmpTrapPort\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_jwsSnmpTrapServerIP(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    in_addr_t trap_server_ip;
    struct in_addr _trap_server_ip;
    char str[100];
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            ret = ubus_invoke_command("snmp", "snmp_get", get_ret_handler_cb, 
                                "{\"get_args\":[\"trap_server_ip\"]}");
            if (ret != 0) {
                return SNMP_ERR_NOSUCHNAME;
            }

            trap_server_ip = inet_addr(jws_read_buf_str());
            snmp_set_var_typed_value(requests->requestvb, ASN_IPADDRESS,
                                     (u_char *) &trap_server_ip,
                                     4);
            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        case MODE_SET_RESERVE1:
                /* or you could use netsnmp_check_vb_type_and_size instead */
            ret = netsnmp_check_vb_type(requests->requestvb, ASN_IPADDRESS);
            if ( ret != SNMP_ERR_NOERROR ) {
                netsnmp_set_request_error(reqinfo, requests, ret );
            }
            break;

        case MODE_SET_RESERVE2:
            /* XXX malloc "undo" storage buffer */
            if (0/* XXX if malloc, or whatever, failed: */) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_RESOURCEUNAVAILABLE);
            }
            break;

        case MODE_SET_FREE:
            /* XXX: free resources allocated in RESERVE1 and/or
               RESERVE2.  Something failed somewhere, and the states
               below won't be called. */
            break;

        case MODE_SET_ACTION:
            memcpy((char *)&_trap_server_ip,  (char *)requests->requestvb->val.integer, 4);
            snprintf(str, sizeof(str), "{\"set_args\":[{\"trap_server_ip\":\"%s\"}]}", inet_ntoa(_trap_server_ip));
            ret = ubus_invoke_command("snmp", "snmp_set", set_ret_handler_cb, str);
            if (ret != 0) {
                return SNMP_ERR_NOSUCHNAME;
            }
            /* XXX: perform the value change here */
            if (0/* XXX: error? */) {
                //netsnmp_set_request_error(reqinfo, requests, /* some error */);
            }
            break;

        case MODE_SET_COMMIT:
            /* XXX: delete temporary storage */
            if (0/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_COMMITFAILED);
            }
            break;

        case MODE_SET_UNDO:
            /* XXX: UNDO and return to previous value for the object */
            if (0/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_UNDOFAILED);
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_jwsSnmpTrapServerIP\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
