/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "jwsDevFactoryInfo.h"

#include "jws_convert.h"
#include "jws_ubus_if.h"

/** Initializes the jwsDevFactoryInfo module */
void
init_jwsDevFactoryInfo(void)
{
    static oid jwsSerialNumber_oid[] = { 1,3,6,1,4,1,33444,2,2,1,2,1 };
    static oid jwsBurnedInMacAddress_oid[] = { 1,3,6,1,4,1,33444,2,2,1,2,2 };

  DEBUGMSGTL(("jwsDevFactoryInfo", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("jwsSerialNumber", handle_jwsSerialNumber,
                               jwsSerialNumber_oid, OID_LENGTH(jwsSerialNumber_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("jwsBurnedInMacAddress", handle_jwsBurnedInMacAddress,
                               jwsBurnedInMacAddress_oid, OID_LENGTH(jwsBurnedInMacAddress_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_jwsSerialNumber(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     (u_char *)"don't be defined",
                                     16);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_jwsSerialNumber\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_jwsBurnedInMacAddress(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    char mac_addr[6];
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            ret = ubus_invoke_command("sysinfo", "sysinfo_get", sysinfo_ret_handler_cb, 
                                "{\"get_args\":[\"mac_addr\"]}");
            if (ret != 0) {
                return SNMP_ERR_NOSUCHNAME;
            }

            convert_str2array(jws_read_buf_str(), mac_addr, 6);

            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     (u_char *) mac_addr,
                                     6);


            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_jwsBurnedInMacAddress\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
