/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "jwsDevGeneral.h"

#include "jws_ubus_if.h"
#include "stdlib.h"
#include "jwslog.h"
#include "jwsTrapPortStatus.h"
#include "jwsTrapPortRateThreshold.h"
#include "jwsTrapPowerSupply.h"
#include "jwsTrapPowerChannelStatus.h"
#include "jwsDevBaseInfo.h"
#include "jws_convert.h"

/** Initializes the jwsDevGeneral module */
void
init_jwsDevGeneral(void)
{
    ubus_client_init();
    init_jwsTrapPortStatus();
    init_jwsTrapPortRateThreshold();
    init_jwsTrapPowerSupply();
    init_jwsTrapPowerChannelStatus();

    static oid jwsDevModelName_oid[] = { 1,3,6,1,4,1,33444,2,2,1,1,1 };
    static oid jwsDevModelId_oid[] = { 1,3,6,1,4,1,33444,2,2,1,1,2 };
    static oid jwsSysDescription_oid[] = { 1,3,6,1,4,1,33444,2,2,1,1,3 };
    static oid jwsSysName_oid[] = { 1,3,6,1,4,1,33444,2,2,1,1,4 };
    static oid jwsSysLocation_oid[] = { 1,3,6,1,4,1,33444,2,2,1,1,5 };
    static oid jwsSysUptime_oid[] = { 1,3,6,1,4,1,33444,2,2,1,1,6 };
    static oid jwsHardwareVersion_oid[] = { 1,3,6,1,4,1,33444,2,2,1,1,7 };
    static oid jwsBootloaderVersion_oid[] = { 1,3,6,1,4,1,33444,2,2,1,1,8 };
    static oid jwsSoftwareVersion_oid[] = { 1,3,6,1,4,1,33444,2,2,1,1,9 };
    static oid jwsResetSystemAction_oid[] = { 1,3,6,1,4,1,33444,2,2,1,1,10 };
    static oid jwsSaveConfigAction_oid[] = { 1,3,6,1,4,1,33444,2,2,1,1,11 };
    static oid jwsSaveConfigStatus_oid[] = { 1,3,6,1,4,1,33444,2,2,1,1,12 };
    static oid jwsClearConfigAction_oid[] = { 1,3,6,1,4,1,33444,2,2,1,1,13 };
    static oid jwsClearConfigStatus_oid[] = { 1,3,6,1,4,1,33444,2,2,1,1,14 };
    static oid jwsPowerSupplyStatus_oid[] = { 1,3,6,1,4,1,33444,2,2,1,1,15 };

  DEBUGMSGTL(("jwsDevGeneral", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("jwsDevModelName", handle_jwsDevModelName,
                               jwsDevModelName_oid, OID_LENGTH(jwsDevModelName_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("jwsDevModelId", handle_jwsDevModelId,
                               jwsDevModelId_oid, OID_LENGTH(jwsDevModelId_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("jwsSysDescription", handle_jwsSysDescription,
                               jwsSysDescription_oid, OID_LENGTH(jwsSysDescription_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("jwsSysName", handle_jwsSysName,
                               jwsSysName_oid, OID_LENGTH(jwsSysName_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("jwsSysLocation", handle_jwsSysLocation,
                               jwsSysLocation_oid, OID_LENGTH(jwsSysLocation_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("jwsSysUptime", handle_jwsSysUptime,
                               jwsSysUptime_oid, OID_LENGTH(jwsSysUptime_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("jwsHardwareVersion", handle_jwsHardwareVersion,
                               jwsHardwareVersion_oid, OID_LENGTH(jwsHardwareVersion_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("jwsBootloaderVersion", handle_jwsBootloaderVersion,
                               jwsBootloaderVersion_oid, OID_LENGTH(jwsBootloaderVersion_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("jwsSoftwareVersion", handle_jwsSoftwareVersion,
                               jwsSoftwareVersion_oid, OID_LENGTH(jwsSoftwareVersion_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("jwsResetSystemAction", handle_jwsResetSystemAction,
                               jwsResetSystemAction_oid, OID_LENGTH(jwsResetSystemAction_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("jwsSaveConfigAction", handle_jwsSaveConfigAction,
                               jwsSaveConfigAction_oid, OID_LENGTH(jwsSaveConfigAction_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("jwsSaveConfigStatus", handle_jwsSaveConfigStatus,
                               jwsSaveConfigStatus_oid, OID_LENGTH(jwsSaveConfigStatus_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("jwsClearConfigAction", handle_jwsClearConfigAction,
                               jwsClearConfigAction_oid, OID_LENGTH(jwsClearConfigAction_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("jwsClearConfigStatus", handle_jwsClearConfigStatus,
                               jwsClearConfigStatus_oid, OID_LENGTH(jwsClearConfigStatus_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
         netsnmp_create_handler_registration("jwsPowerSupplyStatus", handle_jwsPowerSupplyStatus,
                                jwsPowerSupplyStatus_oid, OID_LENGTH(jwsPowerSupplyStatus_oid),
                                HANDLER_CAN_RONLY
         ));
}

int
handle_jwsDevModelName(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;

    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:

            ret = ubus_invoke_command("sysinfo", "sysinfo_get", sysinfo_ret_handler_cb, 
                                "{\"get_args\":[\"model_name\"]}");
            if (ret != 0) {
                return SNMP_ERR_NOSUCHNAME;
            }

            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     (u_char *) jws_read_buf_str(),
                                     strlen(jws_read_buf_str()));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_jwsDevModelName\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_jwsDevModelId(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:

            ret = ubus_invoke_command("sysinfo", "sysinfo_get", sysinfo_ret_handler_cb, 
                                "{\"get_args\":[\"unique_id\"]}");
            if (ret != 0) {
                return SNMP_ERR_NOSUCHNAME;
            }

            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     (u_char *) jws_read_buf_str(),
                                     strlen(jws_read_buf_str()));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_jwsDevModelId\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_jwsSysDescription(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            ret = ubus_invoke_command("sysinfo", "sysinfo_get", sysinfo_ret_handler_cb, 
                                "{\"get_args\":[\"description\"]}");
            if (ret != 0) {
                return SNMP_ERR_NOSUCHNAME;
            }

            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     (u_char *) jws_read_buf_str(),
                                     strlen(jws_read_buf_str()));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_jwsSysDescription\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_jwsSysName(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    char str[256];
    char value[65];
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:

            ret = ubus_invoke_command("sysinfo", "sysinfo_get", sysinfo_ret_handler_cb, 
                                "{\"get_args\":[\"sys_name\"]}");
            if (ret != 0) {
                return SNMP_ERR_NOSUCHNAME;
            }

            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     (u_char *) jws_read_buf_str(),
                                     strlen(jws_read_buf_str()));
            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        case MODE_SET_RESERVE1:
                /* or you could use netsnmp_check_vb_type_and_size instead */
            ret = netsnmp_check_vb_type_and_max_size(requests->requestvb, ASN_OCTET_STR, 64);
            if ( ret != SNMP_ERR_NOERROR ) {
                netsnmp_set_request_error(reqinfo, requests, ret );
            }
            break;

        case MODE_SET_RESERVE2:
            /* XXX malloc "undo" storage buffer */
            if (0/* XXX if malloc, or whatever, failed: */) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_RESOURCEUNAVAILABLE);
            }
            break;

        case MODE_SET_FREE:
            /* XXX: free resources allocated in RESERVE1 and/or
               RESERVE2.  Something failed somewhere, and the states
               below won't be called. */
            break;

        case MODE_SET_ACTION:
            bzero(value, sizeof(value));
            memcpy(value,requests->requestvb->val.string,requests->requestvb->val_len);
            snprintf(str, sizeof(str), "{\"set_args\":[{\"sys_name\":\"%s\"}]}", value);
            ret = ubus_invoke_command("sysinfo", "sysinfo_set", set_ret_handler_cb, str);
            if (ret != 0) {
                return SNMP_ERR_NOSUCHNAME;
            }
            /* XXX: perform the value change here */
            if (0/* XXX: error? */) {
                //netsnmp_set_request_error(reqinfo, requests, /* some error */);
            }
            break;

        case MODE_SET_COMMIT:
            /* XXX: delete temporary storage */
            if (0/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_COMMITFAILED);
            }
            break;

        case MODE_SET_UNDO:
            /* XXX: UNDO and return to previous value for the object */
            if (0/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_UNDOFAILED);
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_jwsSysName\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_jwsSysLocation(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    char str[256];
    char value[65];
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            ret = ubus_invoke_command("sysinfo", "sysinfo_get", sysinfo_ret_handler_cb, 
                                "{\"get_args\":[\"sys_location\"]}");
            if (ret != 0) {
                return SNMP_ERR_NOSUCHNAME;
            }

            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     (u_char *) jws_read_buf_str(),
                                     strlen(jws_read_buf_str()));
            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        case MODE_SET_RESERVE1:
                /* or you could use netsnmp_check_vb_type_and_size instead */
            ret = netsnmp_check_vb_type_and_max_size(requests->requestvb, ASN_OCTET_STR, 64);
            if ( ret != SNMP_ERR_NOERROR ) {
                netsnmp_set_request_error(reqinfo, requests, ret );
            }
            break;

        case MODE_SET_RESERVE2:
            /* XXX malloc "undo" storage buffer */
            if (0/* XXX if malloc, or whatever, failed: */) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_RESOURCEUNAVAILABLE);
            }
            break;

        case MODE_SET_FREE:
            /* XXX: free resources allocated in RESERVE1 and/or
               RESERVE2.  Something failed somewhere, and the states
               below won't be called. */
            break;

        case MODE_SET_ACTION:
            bzero(value, sizeof(value));
            memcpy(value,requests->requestvb->val.string,requests->requestvb->val_len);
            snprintf(str, sizeof(str), "{\"set_args\":[{\"sys_location\":\"%s\"}]}", value);
            ret = ubus_invoke_command("sysinfo", "sysinfo_set", set_ret_handler_cb, str);
            if (ret != 0) {
                return SNMP_ERR_NOSUCHNAME;
            }
            /* XXX: perform the value change here */
            if (0/* XXX: error? */) {
                //netsnmp_set_request_error(reqinfo, requests, /* some error */);
            }
            break;

        case MODE_SET_COMMIT:
            /* XXX: delete temporary storage */
            if (0/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_COMMITFAILED);
            }
            break;

        case MODE_SET_UNDO:
            /* XXX: UNDO and return to previous value for the object */
            if (0/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_UNDOFAILED);
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_jwsSysLocation\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_jwsSysUptime(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    int data;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            ret = ubus_invoke_command("sysinfo", "sysinfo_get", sysinfo_ret_handler_cb, 
                                "{\"get_args\":[\"sys_uptime\"]}");
            if (ret != 0) {
                    return SNMP_ERR_NOSUCHNAME;
            }
            data = atoi(jws_read_buf_str());

            snmp_set_var_typed_value(requests->requestvb, ASN_TIMETICKS,
                                     (u_char *) &data,
                                     sizeof(data));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_jwsSysUptime\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_jwsHardwareVersion(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            ret = ubus_invoke_command("sysinfo", "sysinfo_get", sysinfo_ret_handler_cb, 
                                "{\"get_args\":[\"hardware_version\"]}");
            if (ret != 0)
            {
                    return SNMP_ERR_NOSUCHNAME;
            }

            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     (u_char *) jws_read_buf_str(),
                                     strlen(jws_read_buf_str()));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_jwsHardwareVersion\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_jwsBootloaderVersion(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            ret = ubus_invoke_command("sysinfo", "sysinfo_get", sysinfo_ret_handler_cb, 
                                "{\"get_args\":[\"bootloader_version\"]}");
            if (ret != 0)
            {
                    return SNMP_ERR_NOSUCHNAME;
            }

            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     (u_char *) jws_read_buf_str(),
                                     strlen(jws_read_buf_str()));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_jwsBootloaderVersion\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_jwsSoftwareVersion(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            ret = ubus_invoke_command("sysinfo", "sysinfo_get", sysinfo_ret_handler_cb, 
                                "{\"get_args\":[\"software_version\"]}");
            if (ret != 0)
            {
                    return SNMP_ERR_NOSUCHNAME;
            }

            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     (u_char *) jws_read_buf_str(),
                                     strlen(jws_read_buf_str()));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_jwsSoftwareVersion\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_jwsResetSystemAction(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    static int data = 1;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     (u_char *) &data,
                                     sizeof(data));
            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        case MODE_SET_RESERVE1:
                /* or you could use netsnmp_check_vb_type_and_size instead */
            ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
            if ( ret != SNMP_ERR_NOERROR ) {
                netsnmp_set_request_error(reqinfo, requests, ret );
            }
            break;

        case MODE_SET_RESERVE2:
            /* XXX malloc "undo" storage buffer */
            if (0/* XXX if malloc, or whatever, failed: */) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_RESOURCEUNAVAILABLE);
            }
            break;

        case MODE_SET_FREE:
            /* XXX: free resources allocated in RESERVE1 and/or
               RESERVE2.  Something failed somewhere, and the states
               below won't be called. */
            break;

        case MODE_SET_ACTION:
            data = *requests->requestvb->val.integer;
            system("/etc/init.d/snmpd stop");
            system("reboot -d 2");
            /* XXX: perform the value change here */
            if (0/* XXX: error? */) {
                //netsnmp_set_request_error(reqinfo, requests, /* some error */);
            }
            break;

        case MODE_SET_COMMIT:
            /* XXX: delete temporary storage */
            if (0/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_COMMITFAILED);
            }
            break;

        case MODE_SET_UNDO:
            /* XXX: UNDO and return to previous value for the object */
            if (0/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_UNDOFAILED);
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_jwsResetSystemAction\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_jwsSaveConfigAction(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    int data;
    char str[100];
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            ret = ubus_invoke_command("sysinfo", "sysinfo_get", sysinfo_ret_handler_cb, 
                                "{\"get_args\":[\"save_config\"]}");
            if (ret != 0)
            {
                    return SNMP_ERR_NOSUCHNAME;
            }
            data = atoi(jws_read_buf_str());

            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     (u_char *) &data,
                                     sizeof(data));
            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        case MODE_SET_RESERVE1:
                /* or you could use netsnmp_check_vb_type_and_size instead */
            ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
            if ( ret != SNMP_ERR_NOERROR ) {
                netsnmp_set_request_error(reqinfo, requests, ret );
            }
            break;

        case MODE_SET_RESERVE2:
            /* XXX malloc "undo" storage buffer */
            if (0/* XXX if malloc, or whatever, failed: */) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_RESOURCEUNAVAILABLE);
            }
            break;

        case MODE_SET_FREE:
            /* XXX: free resources allocated in RESERVE1 and/or
               RESERVE2.  Something failed somewhere, and the states
               below won't be called. */
            break;

        case MODE_SET_ACTION:
            data = *requests->requestvb->val.integer;
            snprintf(str, sizeof(str), "{\"set_args\":[{\"save_config\":\"%d\"}]}", data);
            ret = ubus_invoke_command("sysinfo", "sysinfo_set", set_ret_handler_cb, str);
            if (ret != 0) {
                return SNMP_ERR_NOSUCHNAME;
            }
            /* XXX: perform the value change here */
            if (0/* XXX: error? */) {
                //netsnmp_set_request_error(reqinfo, requests, /* some error */);
            }
            break;

        case MODE_SET_COMMIT:
            /* XXX: delete temporary storage */
            if (0/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_COMMITFAILED);
            }
            break;

        case MODE_SET_UNDO:
            /* XXX: UNDO and return to previous value for the object */
            if (0/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_UNDOFAILED);
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_jwsSaveConfigAction\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_jwsSaveConfigStatus(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int data;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     (u_char *) &data,
                                     sizeof(data));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_jwsSaveConfigStatus\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_jwsClearConfigAction(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    int data;
    char str[100];
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            ret = ubus_invoke_command("sysinfo", "sysinfo_get", sysinfo_ret_handler_cb, 
                                "{\"get_args\":[\"clear_config\"]}");
            if (ret != 0)
            {
                    return SNMP_ERR_NOSUCHNAME;
            }
            data = atoi(jws_read_buf_str());

            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     (u_char *) &data,
                                     sizeof(data));
            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        case MODE_SET_RESERVE1:
                /* or you could use netsnmp_check_vb_type_and_size instead */
            ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
            if ( ret != SNMP_ERR_NOERROR ) {
                netsnmp_set_request_error(reqinfo, requests, ret );
            }
            break;

        case MODE_SET_RESERVE2:
            /* XXX malloc "undo" storage buffer */
            if (0/* XXX if malloc, or whatever, failed: */) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_RESOURCEUNAVAILABLE);
            }
            break;

        case MODE_SET_FREE:
            /* XXX: free resources allocated in RESERVE1 and/or
               RESERVE2.  Something failed somewhere, and the states
               below won't be called. */
            break;

        case MODE_SET_ACTION:
            data = *requests->requestvb->val.integer;
            snprintf(str, sizeof(str), "{\"set_args\":[{\"clear_config\":\"%d\"}]}", data);
            ret = ubus_invoke_command("sysinfo", "sysinfo_set", set_ret_handler_cb, str);
            if (ret != 0) {
                return SNMP_ERR_NOSUCHNAME;
            }
            /* XXX: perform the value change here */
            if (0/* XXX: error? */) {
                //netsnmp_set_request_error(reqinfo, requests, /* some error */);
            }
            break;

        case MODE_SET_COMMIT:
            /* XXX: delete temporary storage */
            if (0/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_COMMITFAILED);
            }
            break;

        case MODE_SET_UNDO:
            /* XXX: UNDO and return to previous value for the object */
            if (0/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_UNDOFAILED);
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_jwsClearConfigAction\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_jwsClearConfigStatus(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int data;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     (u_char *) &data,
                                     sizeof(data));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_jwsClearConfigStatus\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_jwsPowerSupplyStatus(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{   
    int ret;
    enum PW_SUPPLY_STATUS pow1Status;
    enum PW_SUPPLY_STATUS pow2Status;
    enum PWSTATUS cur_pwStatus = PW1FAIL_AND_PW2FAIL;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */

    switch(reqinfo->mode) {

        case MODE_GET:

            ret = power_a_get((int *)&pow2Status);
            if (0 != ret){
                return SNMP_ERR_NOSUCHNAME;
            }

            ret = power_b_get((int *)&pow1Status);
            if (0 != ret){
                return SNMP_ERR_NOSUCHNAME;
            }

            if(PW_SUPPLY_ON == pow1Status && PW_SUPPLY_ON == pow2Status){
                cur_pwStatus = PW1OK_AND_PW2OK;
            }else if(PW_SUPPLY_ON == pow1Status && PW_SUPPLY_OFF == pow2Status){
                cur_pwStatus = PW1OK_AND_PW2FAIL;
            }else if (PW_SUPPLY_OFF == pow1Status && PW_SUPPLY_ON == pow2Status){
                cur_pwStatus = PW1FAIL_AND_PW2OK;
            }else{
                cur_pwStatus = PW1FAIL_AND_PW2FAIL;
            }
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                    (u_char *) &cur_pwStatus,
                                    sizeof(cur_pwStatus));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_jwsPowerSupplyStatus\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
