/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17821 2009-11-11 09:00:00Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "jwsFdbPortSecurityGroup.h"

#include "jws_ubus_if.h"
#include "jwsDevBaseInfo.h"
#include "jws_convert.h"
#include "jwslog.h"

/* create a new row in the (unsorted) table */
struct jwsFdbSecurePortTable_entry *
jwsFdbSecurePortTable_createEntry(
                 long  jwsFdbSecurePortIndex
                );
/* create a new row in the (unsorted) table */
struct jwsFdbSecureAddrTable_entry *
jwsFdbSecureAddrTable_createEntry(
                 long  jwsFdbSecureAddrIndex,
                 struct jwsFdbSecureAddrTable_entry *table_entry
                );
int jwsFdbSecureAddrTable_load(netsnmp_cache *cache, void *magic);
void jwsFdbSecureAddrTable_free(netsnmp_cache *cache, void *magic);
void jwsFdbSecureAddrTable_removeTable( void );

/** Initializes the jwsFdbPortSecurityTables module */
void
init_jwsFdbPortSecurityGroup(void)
{
    static oid jwsFdbSecureAddrNumber_oid[] = { 1,3,6,1,4,1,33444,2,2,6,2,2 };

  DEBUGMSGTL(("jwsFdbPortSecurityGroup", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("jwsFdbSecureAddrNumber", handle_jwsFdbSecureAddrNumber,
                               jwsFdbSecureAddrNumber_oid, OID_LENGTH(jwsFdbSecureAddrNumber_oid),
                               HANDLER_CAN_RONLY
        ));
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_jwsFdbSecurePortTable();
    initialize_table_jwsFdbSecureAddrTable();
}

int
handle_jwsFdbSecureAddrNumber(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    unsigned int entry_num;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:

            ret = ubus_invoke_command("fdb", "fdb_get", get_ret_handler_cb, 
                                "{\"get_args\":[\"entry_num\"]}");
            if (ret != 0) {
                return SNMP_ERR_NOSUCHNAME;
            }

            entry_num = atoi(jws_read_buf_str());

            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     (u_char *) &entry_num,
                                     sizeof(entry_num));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_jwsFdbSecureAddrNumber\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

//  # Determine the first/last column names

/** Initialize the jwsFdbSecurePortTable table by defining its contents and how it's structured */
void
initialize_table_jwsFdbSecurePortTable(void)
{
    static oid jwsFdbSecurePortTable_oid[] = {1,3,6,1,4,1,33444,2,2,6,2,1};
    size_t jwsFdbSecurePortTable_oid_len   = OID_LENGTH(jwsFdbSecurePortTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    int i;
    struct stJwsDevBaseInfo jwsDevBaseInfo;

    reg = netsnmp_create_handler_registration(
              "jwsFdbSecurePortTable",     jwsFdbSecurePortTable_handler,
              jwsFdbSecurePortTable_oid, jwsFdbSecurePortTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: jwsFdbSecurePortIndex */
                           0);
    table_info->min_column = COLUMN_JWSFDBSECUREPORTINDEX;
    table_info->max_column = COLUMN_JWSFDBSECUREPORTENABLE;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = jwsFdbSecurePortTable_get_first_data_point;
    iinfo->get_next_data_point  = jwsFdbSecurePortTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
    getJwsDevBaseInfo(&jwsDevBaseInfo);
    for (i = 1; i <= jwsDevBaseInfo.port_num; ++i)
    {
        jwsFdbSecurePortTable_createEntry(i);
    }
    
}

    /* Typical data structure for a row entry */
struct jwsFdbSecurePortTable_entry {
    /* Index values */
    //long jwsFdbSecurePortIndex;

    /* Column values */
    long jwsFdbSecurePortIndex;
    long jwsFdbSecurePortEnable;
    long old_jwsFdbSecurePortEnable;

    /* Illustrate using a simple linked list */
    int   valid;
    struct jwsFdbSecurePortTable_entry *next;
};

struct jwsFdbSecurePortTable_entry  *jwsFdbSecurePortTable_head;

/* create a new row in the (unsorted) table */
struct jwsFdbSecurePortTable_entry *
jwsFdbSecurePortTable_createEntry(
                 long  jwsFdbSecurePortIndex
                ) {
    struct jwsFdbSecurePortTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct jwsFdbSecurePortTable_entry);
    if (!entry)
        return NULL;

    entry->jwsFdbSecurePortIndex = jwsFdbSecurePortIndex;
    entry->next = jwsFdbSecurePortTable_head;
    jwsFdbSecurePortTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
jwsFdbSecurePortTable_removeEntry( struct jwsFdbSecurePortTable_entry *entry ) {
    struct jwsFdbSecurePortTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = jwsFdbSecurePortTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        jwsFdbSecurePortTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
jwsFdbSecurePortTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = jwsFdbSecurePortTable_head;
    return jwsFdbSecurePortTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
jwsFdbSecurePortTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct jwsFdbSecurePortTable_entry *entry = (struct jwsFdbSecurePortTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->jwsFdbSecurePortIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the jwsFdbSecurePortTable table */
int
jwsFdbSecurePortTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct jwsFdbSecurePortTable_entry          *table_entry;

    int ret = SNMP_ERR_NOERROR;
    int data = 0;
    char str[100] = {0};
    char value[50] = {0};

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsFdbSecurePortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            bzero(str, sizeof(str));
    
            switch (table_info->colnum) {
            case COLUMN_JWSFDBSECUREPORTINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsFdbSecurePortIndex);
                break;
            case COLUMN_JWSFDBSECUREPORTENABLE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsFdbSecurePortIndex, "status");
                ret = ubus_invoke_command("fdb", "fdb_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsFdbSecurePortEnable = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsFdbSecurePortEnable);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsFdbSecurePortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSFDBSECUREPORTENABLE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsFdbSecurePortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            bzero(str, sizeof(str));
    
            switch (table_info->colnum) {
            case COLUMN_JWSFDBSECUREPORTENABLE:
                table_entry->old_jwsFdbSecurePortEnable = table_entry->jwsFdbSecurePortEnable;
                table_entry->jwsFdbSecurePortEnable     = *request->requestvb->val.integer;
                
                snprintf(value, sizeof(value), "%ld", table_entry->jwsFdbSecurePortEnable);
                ubus_set_port_cmd_enc(str, sizeof(str), table_entry->jwsFdbSecurePortIndex, "status", value);
                ret = ubus_invoke_command("fdb", "fdb_set", 
                                    set_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsFdbSecurePortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSFDBSECUREPORTENABLE:
                table_entry->jwsFdbSecurePortEnable     = table_entry->old_jwsFdbSecurePortEnable;
                table_entry->old_jwsFdbSecurePortEnable = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
//  # Determine the first/last column names

/** Initialize the jwsFdbSecureAddrTable table by defining its contents and how it's structured */
void
initialize_table_jwsFdbSecureAddrTable(void)
{
    static oid jwsFdbSecureAddrTable_oid[] = {1,3,6,1,4,1,33444,2,2,6,2,3};
    size_t jwsFdbSecureAddrTable_oid_len   = OID_LENGTH(jwsFdbSecureAddrTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    reg = netsnmp_create_handler_registration(
              "jwsFdbSecureAddrTable",     jwsFdbSecureAddrTable_handler,
              jwsFdbSecureAddrTable_oid, jwsFdbSecureAddrTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: jwsFdbSecureAddrIndex */
                           0);
    table_info->min_column = COLUMN_JWSFDBSECUREADDRINDEX;
    table_info->max_column = COLUMN_JWSFDBSECUREADDRROWSTATUS;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = jwsFdbSecureAddrTable_get_first_data_point;
    iinfo->get_next_data_point  = jwsFdbSecureAddrTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
    netsnmp_inject_handler( reg,
            netsnmp_get_cache_handler(1,
                    jwsFdbSecureAddrTable_load, jwsFdbSecureAddrTable_free,
                    jwsFdbSecureAddrTable_oid, jwsFdbSecureAddrTable_oid_len));
}

    /* Typical data structure for a row entry */
struct jwsFdbSecureAddrTable_entry {
    /* Index values */
//    long jwsFdbSecureAddrIndex;

    /* Column values */
    long jwsFdbSecureAddrIndex;
    long old_jwsFdbSecureAddrIndex;
    long jwsFdbSecureAddrPortId;
    long old_jwsFdbSecureAddrPortId;
#define MAC_LEN     (6)
    char jwsFdbSecureAddrMacAddress[MAC_LEN];
    size_t jwsFdbSecureAddrMacAddress_len;
    char old_jwsFdbSecureAddrMacAddress[MAC_LEN];
    size_t old_jwsFdbSecureAddrMacAddress_len;
    long jwsFdbSecureAddrRowStatus;

    /* Illustrate using a simple linked list */
    int   valid;
    struct jwsFdbSecureAddrTable_entry *next;
};

struct jwsFdbSecureAddrTable_entry  *jwsFdbSecureAddrTable_head;

int jwsFdbSecureAddrTable_load(netsnmp_cache *cache, void *magic)
{
    int ret;
    int i, entry_num;
    struct jwsFdbSecureAddrTable_entry table_entry;

    ret = ubus_invoke_command("fdb", "fdb_get", get_ret_handler_cb, 
                                "{\"get_args\":[\"entry_num\"]}");
    if (ret != 0) {
        LogWrite(ERROR, "file:%s line:%d func:%s, invoke get_args entry_num failed\n",
                        __FILENAME__, __LINE__, __FUNCTION__);
        return -1;
    }

    entry_num = atoi(jws_read_buf_str());
    if (entry_num == -1)
    {
        LogWrite(ERROR, "file:%s line:%d func:%s, Fdbsecure port disable\n",
                        __FILENAME__, __LINE__, __FUNCTION__);
        return -1;
    }

    jwsFdbSecureAddrTable_removeTable();
         
    for (i = 1; i <= entry_num; i++) {
        table_entry.jwsFdbSecureAddrRowStatus = 1;
        jwsFdbSecureAddrTable_createEntry(i, &table_entry);
    }

    return 0;
}

void jwsFdbSecureAddrTable_free(netsnmp_cache *cache, void *magic)
{
    jwsFdbSecureAddrTable_removeTable();
}

/* create a new row in the (unsorted) table */
struct jwsFdbSecureAddrTable_entry *
jwsFdbSecureAddrTable_createEntry(
                 long  jwsFdbSecureAddrIndex,
                 struct jwsFdbSecureAddrTable_entry *table_entry
                ) {
    struct jwsFdbSecureAddrTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct jwsFdbSecureAddrTable_entry);
    if (!entry)
        return NULL;

    entry->jwsFdbSecureAddrIndex = jwsFdbSecureAddrIndex;

    if (NULL != table_entry)
    {
        entry->jwsFdbSecureAddrRowStatus = table_entry->jwsFdbSecureAddrRowStatus;
    }

    entry->next = jwsFdbSecureAddrTable_head;
    jwsFdbSecureAddrTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
jwsFdbSecureAddrTable_removeEntry( struct jwsFdbSecureAddrTable_entry *entry ) {
    struct jwsFdbSecureAddrTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = jwsFdbSecureAddrTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        jwsFdbSecureAddrTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}

/* remove a table */
void
jwsFdbSecureAddrTable_removeTable( void ) {
    struct jwsFdbSecureAddrTable_entry *ptr;

    LogWrite(DEBUG, "file:%s line:%d func:%s, remove table\n",
                        __FILENAME__, __LINE__, __FUNCTION__);
    for ( ptr  = jwsFdbSecureAddrTable_head; ptr != NULL; ptr = ptr->next ) {
        jwsFdbSecureAddrTable_removeEntry( ptr );
    }

}

/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
jwsFdbSecureAddrTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = jwsFdbSecureAddrTable_head;
    return jwsFdbSecureAddrTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
jwsFdbSecureAddrTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct jwsFdbSecureAddrTable_entry *entry = (struct jwsFdbSecureAddrTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->jwsFdbSecureAddrIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the jwsFdbSecureAddrTable table */
int
jwsFdbSecureAddrTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct jwsFdbSecureAddrTable_entry          *table_entry;

    struct jwsFdbSecureAddrTable_entry          *table_row = NULL;
    int ret;
    int data;
    char str[100] = {0};
    char value[50];

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsFdbSecureAddrTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            bzero(str, sizeof(str));
    
            switch (table_info->colnum) {
            case COLUMN_JWSFDBSECUREADDRINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsFdbSecureAddrIndex);
                break;
            case COLUMN_JWSFDBSECUREADDRPORTID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_cmd_enc(str, sizeof(str), table_entry->jwsFdbSecureAddrIndex, "port");
                ret = ubus_invoke_command("fdb", "fdb_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsFdbSecureAddrPortId = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsFdbSecureAddrPortId);
                break;
            case COLUMN_JWSFDBSECUREADDRMACADDRESS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_cmd_enc(str, sizeof(str), table_entry->jwsFdbSecureAddrIndex, 
                                "mac_address");
                ret = ubus_invoke_command("fdb", "fdb_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }

                convert_str2array(jws_read_buf_str(), table_entry->jwsFdbSecureAddrMacAddress, 6);
                table_entry->jwsFdbSecureAddrMacAddress_len = 6;

                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->jwsFdbSecureAddrMacAddress,
                                          table_entry->jwsFdbSecureAddrMacAddress_len);
                break;
            case COLUMN_JWSFDBSECUREADDRROWSTATUS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsFdbSecureAddrRowStatus);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsFdbSecureAddrTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSFDBSECUREADDRINDEX:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSFDBSECUREADDRPORTID:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSFDBSECUREADDRMACADDRESS:
	        /* or possiblc 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->jwsFdbSecureAddrMacAddress));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSFDBSECUREADDRROWSTATUS:
                ret = netsnmp_check_vb_rowstatus(request->requestvb,
                         (table_entry ? RS_ACTIVE : RS_NONEXISTENT ));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsFdbSecureAddrTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            bzero(str, sizeof(str));
    
            switch (table_info->colnum) {
            case COLUMN_JWSFDBSECUREADDRROWSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_CREATEANDGO:
                case RS_CREATEANDWAIT:
                    table_row = jwsFdbSecureAddrTable_createEntry(
                        *table_info->indexes->val.integer,
                        NULL
                        );

                    ubus_add_cmd_enc(str, sizeof(str), *table_info->indexes->val.integer);
                    ret = ubus_invoke_command("fdb", "fdb_set", 
                                            set_ret_handler_cb, str);
                    if (ret != 0) {
                        return SNMP_ERR_NOSUCHNAME;
                    }

                    if (table_row) {
                        netsnmp_insert_iterator_context( request, table_row );
                    } else {
                        netsnmp_set_request_error( reqinfo, request,
                                                   SNMP_ERR_RESOURCEUNAVAILABLE );
                        return SNMP_ERR_NOERROR;
                    }
                }
            }
        }
        break;

    case MODE_SET_FREE:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsFdbSecureAddrTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSFDBSECUREADDRROWSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_CREATEANDGO:
                case RS_CREATEANDWAIT:
                    if (table_entry && !table_entry->valid) {
                        jwsFdbSecureAddrTable_removeEntry( table_row );
                    }
                }
            }
        }
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsFdbSecureAddrTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            bzero(str, sizeof(str));
    
            switch (table_info->colnum) {
            case COLUMN_JWSFDBSECUREADDRINDEX:
                table_entry->old_jwsFdbSecureAddrIndex = table_entry->jwsFdbSecureAddrIndex;
                table_entry->jwsFdbSecureAddrIndex     = *request->requestvb->val.integer;
                break;
            case COLUMN_JWSFDBSECUREADDRPORTID:
                table_entry->old_jwsFdbSecureAddrPortId = table_entry->jwsFdbSecureAddrPortId;
                table_entry->jwsFdbSecureAddrPortId     = *request->requestvb->val.integer;

                snprintf(value, sizeof(value), "%ld", table_entry->jwsFdbSecureAddrPortId);
                ubus_set_cmd_enc(str, sizeof(str), table_entry->jwsFdbSecureAddrIndex, 
                    "port", value);
                ret = ubus_invoke_command("fdb", "fdb_set", 
                                    set_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSFDBSECUREADDRMACADDRESS:
                memcpy( table_entry->old_jwsFdbSecureAddrMacAddress,
                        table_entry->jwsFdbSecureAddrMacAddress,
                        sizeof(table_entry->jwsFdbSecureAddrMacAddress));
                table_entry->old_jwsFdbSecureAddrMacAddress_len =
                        table_entry->jwsFdbSecureAddrMacAddress_len;
                memset( table_entry->jwsFdbSecureAddrMacAddress, 0,
                        sizeof(table_entry->jwsFdbSecureAddrMacAddress));
                memcpy( table_entry->jwsFdbSecureAddrMacAddress,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->jwsFdbSecureAddrMacAddress_len =
                        request->requestvb->val_len;

                convert_array2str(table_entry->jwsFdbSecureAddrMacAddress, 6, value, 3*6);
                ubus_set_cmd_enc(str, sizeof(str), table_entry->jwsFdbSecureAddrIndex, 
                                "mac_address", value);
                ret = ubus_invoke_command("fdb", "fdb_set", 
                                        set_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            }
        }
        /* Check the internal consistency of an active row */
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsFdbSecureAddrTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSFDBSECUREADDRROWSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_ACTIVE:
                case RS_CREATEANDGO:
                    if (0/* XXX */) {
                        netsnmp_set_request_error( reqinfo, request,
                                                   SNMP_ERR_INCONSISTENTVALUE );
                        return SNMP_ERR_NOERROR;
                    }
                }
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsFdbSecureAddrTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSFDBSECUREADDRINDEX:
                table_entry->jwsFdbSecureAddrIndex     = table_entry->old_jwsFdbSecureAddrIndex;
                table_entry->old_jwsFdbSecureAddrIndex = 0;
                break;
            case COLUMN_JWSFDBSECUREADDRPORTID:
                table_entry->jwsFdbSecureAddrPortId     = table_entry->old_jwsFdbSecureAddrPortId;
                table_entry->old_jwsFdbSecureAddrPortId = 0;
                break;
            case COLUMN_JWSFDBSECUREADDRMACADDRESS:
                memcpy( table_entry->jwsFdbSecureAddrMacAddress,
                        table_entry->old_jwsFdbSecureAddrMacAddress,
                        sizeof(table_entry->jwsFdbSecureAddrMacAddress));
                memset( table_entry->old_jwsFdbSecureAddrMacAddress, 0,
                        sizeof(table_entry->jwsFdbSecureAddrMacAddress));
                table_entry->jwsFdbSecureAddrMacAddress_len =
                        table_entry->old_jwsFdbSecureAddrMacAddress_len;
                break;
            case COLUMN_JWSFDBSECUREADDRROWSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_CREATEANDGO:
                case RS_CREATEANDWAIT:
                    if (table_entry && !table_entry->valid) {
                        jwsFdbSecureAddrTable_removeEntry( table_row );
                    }
                }
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsFdbSecureAddrTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSFDBSECUREADDRROWSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_CREATEANDGO:
                    table_entry->valid = 1;
                    /* Fall-through */
                case RS_ACTIVE:
                    table_entry->jwsFdbSecureAddrRowStatus = RS_ACTIVE;
                    break;

                case RS_CREATEANDWAIT:
                    table_entry->valid = 1;
                    /* Fall-through */
                case RS_NOTINSERVICE:
                    table_entry->jwsFdbSecureAddrRowStatus = RS_NOTINSERVICE;
                    break;

                case RS_DESTROY:
                    ubus_clear_cmd_enc(str, sizeof(str), *table_info->indexes->val.integer);
                    ret = ubus_invoke_command("fdb", "fdb_clear", 
                                            clear_ret_handler_cb, str);
                    if (ret != 0) {
                        return SNMP_ERR_NOSUCHNAME;
                    }
                    jwsFdbSecureAddrTable_removeEntry( table_row );
                }
            }
        }
        break;
    }
    return SNMP_ERR_NOERROR;
}
