/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17821 2009-11-11 09:00:00Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "jwsIfExtPortTable.h"
#include "jws_ubus_if.h"
#include "stdlib.h"
#include "jwsDevBaseInfo.h"
#include "jwslog.h"

#include "gpio_i2c.h"
#include <sys/ioctl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>

static int i2c_fd = -1;
static struct stJwsDevBaseInfo jwsDevBaseInfo;

/* create a new row in the (unsorted) table */
struct jwsIfExtPortTable_entry *
jwsIfExtPortTable_createEntry(long  jwsIfExtPortIfIndex) ;

/** Initializes the jwsIfExtPortTable module */
void
init_jwsIfExtPortTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_jwsIfExtPortTable();
}

static int i2c_read(const int fd, const unsigned int devaddr,
        const unsigned int regaddr, char *reg_value)
{
    unsigned int value = 0;
    int ret;

    value = ((devaddr & 0xff) << 24)|((regaddr & 0xff) << 16);
    ret = ioctl(fd, GPIO_I2C_READ, &value);
    *reg_value = value & 0xff;

    return ret;
}

//  # Determine the first/last column names

/** Initialize the jwsIfExtPortTable table by defining its contents and how it's structured */
void
initialize_table_jwsIfExtPortTable(void)
{
    static oid jwsIfExtPortTable_oid[] = {1,3,6,1,4,1,33444,2,2,2,1,1};
    size_t jwsIfExtPortTable_oid_len   = OID_LENGTH(jwsIfExtPortTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    int i;

    reg = netsnmp_create_handler_registration(
              "jwsIfExtPortTable",     jwsIfExtPortTable_handler,
              jwsIfExtPortTable_oid, jwsIfExtPortTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: jwsIfExtPortIfIndex */
                           0);
    table_info->min_column = COLUMN_JWSIFEXTPORTIFINDEX;
    table_info->max_column = COLUMN_JWSIFEXTPORTFLOWCONTROLMODE;

    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = jwsIfExtPortTable_get_first_data_point;
    iinfo->get_next_data_point  = jwsIfExtPortTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;

    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
    getJwsDevBaseInfo(&jwsDevBaseInfo);
    if(0 == strcmp(jwsDevBaseInfo.serial_num, "54-10-01-06-01-01-00-00") ||
       0 == strcmp(jwsDevBaseInfo.serial_num, "54-20-01-06-01-02-00-00") )
    {
        i2c_fd = open("/dev/gpioi2c", 0);
        if (i2c_fd<0)
        {
            LogWrite(ERROR, "file:%s line:%d func:%s, Open gpioi2c dev error!\n",
                    __FILENAME__, __LINE__, __FUNCTION__);
        }
        for (i = 1; i <= jwsDevBaseInfo.port_num + 4; i++)
        {
            jwsIfExtPortTable_createEntry(i);
        }

    }else{

        for (i = 1; i <= jwsDevBaseInfo.port_num; i++)
        {
            jwsIfExtPortTable_createEntry(i);
        }
    }
}

    /* Typical data structure for a row entry */
struct jwsIfExtPortTable_entry {
    /* Index values */
//    long jwsIfExtPortIfIndex;

    /* Column values */
    long jwsIfExtPortIfIndex;
    long jwsIfExtPortType;
    long jwsIfExtPortAdminMode;
    long old_jwsIfExtPortAdminMode;
    long jwsIfExtPortOperState;
    long jwsIfExtPortPhysicalMode;
    long old_jwsIfExtPortPhysicalMode;
    long jwsIfExtPortPhysicalState;
    long jwsIfExtPortFlowControlMode;
    long old_jwsIfExtPortFlowControlMode;
//    long jwsIfExtPortDot1dState;

    /* Illustrate using a simple linked list */
    int   valid;
    struct jwsIfExtPortTable_entry *next;
};

struct jwsIfExtPortTable_entry  *jwsIfExtPortTable_head;

/* create a new row in the (unsorted) table */
struct jwsIfExtPortTable_entry *
jwsIfExtPortTable_createEntry(
                 long  jwsIfExtPortIfIndex
                ) {
    struct jwsIfExtPortTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct jwsIfExtPortTable_entry);
    if (!entry)
        return NULL;

    entry->jwsIfExtPortIfIndex = jwsIfExtPortIfIndex;
    entry->next = jwsIfExtPortTable_head;
    jwsIfExtPortTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
jwsIfExtPortTable_removeEntry( struct jwsIfExtPortTable_entry *entry ) {
    struct jwsIfExtPortTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = jwsIfExtPortTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        jwsIfExtPortTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
jwsIfExtPortTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = jwsIfExtPortTable_head;
    return jwsIfExtPortTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
jwsIfExtPortTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct jwsIfExtPortTable_entry *entry = (struct jwsIfExtPortTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->jwsIfExtPortIfIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the jwsIfExtPortTable table */
int
jwsIfExtPortTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct jwsIfExtPortTable_entry          *table_entry;

    int ret = SNMP_ERR_NOERROR;
    int data = 0;
    char str[100] = {0};
    char value[50] = {0};
    char fpga_reg_value = 0;

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsIfExtPortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            bzero(str, sizeof(str));
    
            switch (table_info->colnum) {
            case COLUMN_JWSIFEXTPORTIFINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsIfExtPortIfIndex);
                break;
            case COLUMN_JWSIFEXTPORTTYPE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                /* OB9331DTA(G1.E4) */
                if(0 == strcmp(jwsDevBaseInfo.serial_num, "54-10-01-06-01-01-00-00"))
                {
                    if(table_entry->jwsIfExtPortIfIndex > jwsDevBaseInfo.port_num)
                    {
                        switch(table_entry->jwsIfExtPortIfIndex)
                        {
                            case 6:
                                /* sdi_in */
                                table_entry->jwsIfExtPortType = 32;
                                break;
                            case 7:
                                /* sdi_out */
                                table_entry->jwsIfExtPortType = 33;
                                break;
                            case 8:
                                /* opt_out */
                                table_entry->jwsIfExtPortType = 35;
                                break;
                            case 9:
                                /* opt_in */
                                table_entry->jwsIfExtPortType = 34;
                                break;
                        }
                    }else{
                        ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsIfExtPortIfIndex, "type");
                        ret = ubus_invoke_command("port_config", "port_config_get", 
                                        port_config_get_ret_handler_cb, str);
                        if (ret != 0)
                        {
                            return SNMP_ERR_NOSUCHNAME;
                        }
                        data = atoi(jws_read_buf_str());
                        table_entry->jwsIfExtPortType = data;
                    }
                    /* OB9331DRA(G1.E4) */
                }else if(0 == strcmp(jwsDevBaseInfo.serial_num, "54-20-01-06-01-02-00-00")){
                    if(table_entry->jwsIfExtPortIfIndex > jwsDevBaseInfo.port_num)
                    {
                        switch(table_entry->jwsIfExtPortIfIndex)
                        {
                            case 6:
                                /* sdi_out */
                                table_entry->jwsIfExtPortType = 33;
                                break;
                            case 7:
                                /* sdi_out */
                                table_entry->jwsIfExtPortType = 33;
                                break;
                            case 8:
                                /* opt_in */
                                table_entry->jwsIfExtPortType = 34;
                                break;
                            case 9:
                                /* opt_out */
                                table_entry->jwsIfExtPortType = 35;
                                break;
                        }
                    }else{
                        ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsIfExtPortIfIndex, "type");
                        ret = ubus_invoke_command("port_config", "port_config_get", 
                                port_config_get_ret_handler_cb, str);
                        if (ret != 0)
                        {
                            return SNMP_ERR_NOSUCHNAME;
                        }
                        data = atoi(jws_read_buf_str());
                        table_entry->jwsIfExtPortType = data;
                    }
                /* Other product */
                }else{
                    ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsIfExtPortIfIndex, "type");
                    ret = ubus_invoke_command("port_config", "port_config_get", 
                                            port_config_get_ret_handler_cb, str);
                    if (ret != 0)
                    {
                        return SNMP_ERR_NOSUCHNAME;
                    }
                    data = atoi(jws_read_buf_str());
                    table_entry->jwsIfExtPortType = data;
                }

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsIfExtPortType);
                break;
            case COLUMN_JWSIFEXTPORTADMINMODE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                if(0 == strcmp(jwsDevBaseInfo.serial_num, "54-10-01-06-01-01-00-00") ||
                   0 == strcmp(jwsDevBaseInfo.serial_num, "54-20-01-06-01-02-00-00") )
                {
                    if(table_entry->jwsIfExtPortIfIndex > jwsDevBaseInfo.port_num)
                    {
                        table_entry->jwsIfExtPortAdminMode = 1;
                    }else{
                        ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsIfExtPortIfIndex, "admin_mode");
                        ret = ubus_invoke_command("port_config", "port_config_get", 
                                            port_config_get_ret_handler_cb, str);
                        if (ret != 0)
                        {
                            return SNMP_ERR_NOSUCHNAME;
                        }
                        data = atoi(jws_read_buf_str());
                        table_entry->jwsIfExtPortAdminMode = data;
                    }
                }else{
                    ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsIfExtPortIfIndex, "admin_mode");
                    ret = ubus_invoke_command("port_config", "port_config_get", 
                                        port_config_get_ret_handler_cb, str);
                    if (ret != 0)
                    {
                        return SNMP_ERR_NOSUCHNAME;
                    }
                    data = atoi(jws_read_buf_str());
                    table_entry->jwsIfExtPortAdminMode = data;
                }

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsIfExtPortAdminMode);
                break;
            case COLUMN_JWSIFEXTPORTOPERSTATE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                /* OB9331DTA(G1.E4) */
                if(0 == strcmp(jwsDevBaseInfo.serial_num, "54-10-01-06-01-01-00-00"))
                {
                    if(table_entry->jwsIfExtPortIfIndex > jwsDevBaseInfo.port_num)
                    {
                        switch(table_entry->jwsIfExtPortIfIndex)
                        {
                            case 6:
                                /* sdi_in */
                                i2c_read(i2c_fd, 0x40, 0x04, &fpga_reg_value);
                                if(1 == (fpga_reg_value & 0x01)){
                                    table_entry->jwsIfExtPortOperState = 1;
                                }else{
                                    table_entry->jwsIfExtPortOperState = 2;
                                }
                                break;
                            case 7:
                                /* sdi_out */
                                i2c_read(i2c_fd, 0x40, 0x07, &fpga_reg_value);
                                if(1 == (fpga_reg_value & 0x01)){
                                    table_entry->jwsIfExtPortOperState = 1;
                                }else{
                                    table_entry->jwsIfExtPortOperState = 2;
                                }
                                break;
                            case 8:
                                /* opt_out */
                                i2c_read(i2c_fd, 0x40, 0x02, &fpga_reg_value);
                                if(1 == (fpga_reg_value & 0x01)){
                                    table_entry->jwsIfExtPortOperState = 1;
                                }else{
                                    table_entry->jwsIfExtPortOperState = 2;
                                }
                                break;
                            case 9:
                                /* opt_in */
                                i2c_read(i2c_fd, 0x40, 0x03, &fpga_reg_value);
                                if(1 == (fpga_reg_value & 0x01)){
                                    table_entry->jwsIfExtPortOperState = 1;
                                }else{
                                    table_entry->jwsIfExtPortOperState = 2;
                                }
                                break;
                        }

                    }else{
                        ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsIfExtPortIfIndex, "operational_status");
                        ret = ubus_invoke_command("port_config", "port_config_get", 
                                                port_config_get_ret_handler_cb, str);
                        if (ret != 0)
                        {
                            return SNMP_ERR_NOSUCHNAME;
                        }
                        data = atoi(jws_read_buf_str());
                        table_entry->jwsIfExtPortOperState = data;
                    }
                /* OB9331DRA(G1.E4) */
                }else if(0 == strcmp(jwsDevBaseInfo.serial_num, "54-20-01-06-01-02-00-00")){
                    if(table_entry->jwsIfExtPortIfIndex > jwsDevBaseInfo.port_num)
                    {
                        switch(table_entry->jwsIfExtPortIfIndex)
                        {
                            case 6:
                                /* sdi_out */
                                i2c_read(i2c_fd, 0x40, 0x07, &fpga_reg_value);
                                if(1 == (fpga_reg_value & 0x01)){
                                    table_entry->jwsIfExtPortOperState = 1;
                                }else{
                                    table_entry->jwsIfExtPortOperState = 2;
                                }
                                break;
                            case 7:
                                /* sdi_out */
                                i2c_read(i2c_fd, 0x40, 0x07, &fpga_reg_value);
                                if(1 == (fpga_reg_value & 0x01)){
                                    table_entry->jwsIfExtPortOperState = 1;
                                }else{
                                    table_entry->jwsIfExtPortOperState = 2;
                                }
                                break;
                            case 8:
                                /* opt_in */
                                i2c_read(i2c_fd, 0x40, 0x02, &fpga_reg_value);
                                if(1 == (fpga_reg_value & 0x01)){
                                    table_entry->jwsIfExtPortOperState = 1;
                                }else{
                                    table_entry->jwsIfExtPortOperState = 2;
                                }
                                break;
                            case 9:
                                /* opt_out */
                                i2c_read(i2c_fd, 0x40, 0x03, &fpga_reg_value);
                                if(1 == (fpga_reg_value & 0x01)){
                                    table_entry->jwsIfExtPortOperState = 1;
                                }else{
                                    table_entry->jwsIfExtPortOperState = 2;
                                }
                                break;
                        }
                    }else{
                        ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsIfExtPortIfIndex, "operational_status");
                        ret = ubus_invoke_command("port_config", "port_config_get", 
                                port_config_get_ret_handler_cb, str);
                        if (ret != 0)
                        {
                            return SNMP_ERR_NOSUCHNAME;
                        }
                        data = atoi(jws_read_buf_str());
                        table_entry->jwsIfExtPortOperState = data;
                    }
                /* Other product */
                }else{
                    ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsIfExtPortIfIndex, "operational_status");
                    ret = ubus_invoke_command("port_config", "port_config_get", 
                                            port_config_get_ret_handler_cb, str);
                    if (ret != 0)
                    {
                        return SNMP_ERR_NOSUCHNAME;
                    }
                    data = atoi(jws_read_buf_str());
                    table_entry->jwsIfExtPortOperState = data;
                }

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsIfExtPortOperState);
                break;
            case COLUMN_JWSIFEXTPORTPHYSICALMODE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                if(0 == strcmp(jwsDevBaseInfo.serial_num, "54-10-01-06-01-01-00-00") ||
                   0 == strcmp(jwsDevBaseInfo.serial_num, "54-20-01-06-01-02-00-00") )
                {
                    if(table_entry->jwsIfExtPortIfIndex > jwsDevBaseInfo.port_num)
                    {
                        table_entry->jwsIfExtPortPhysicalMode = 1;
                    }else{
                        ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsIfExtPortIfIndex, "physical_mode");
                        ret = ubus_invoke_command("port_config", "port_config_get", 
                                                port_config_get_ret_handler_cb, str);
                        if (ret != 0)
                        {
                            return SNMP_ERR_NOSUCHNAME;
                        }
                        data = atoi(jws_read_buf_str());
                        table_entry->jwsIfExtPortPhysicalMode = data;
                    }
                }else{
                    ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsIfExtPortIfIndex, "physical_mode");
                    ret = ubus_invoke_command("port_config", "port_config_get", 
                                            port_config_get_ret_handler_cb, str);
                    if (ret != 0)
                    {
                        return SNMP_ERR_NOSUCHNAME;
                    }
                    data = atoi(jws_read_buf_str());
                    table_entry->jwsIfExtPortPhysicalMode = data;
                }

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsIfExtPortPhysicalMode);
                break;
            case COLUMN_JWSIFEXTPORTPHYSICALSTATE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                if(0 == strcmp(jwsDevBaseInfo.serial_num, "54-10-01-06-01-01-00-00") ||
                   0 == strcmp(jwsDevBaseInfo.serial_num, "54-20-01-06-01-02-00-00") )
                {
                    if(table_entry->jwsIfExtPortIfIndex > jwsDevBaseInfo.port_num)
                    {
                        table_entry->jwsIfExtPortPhysicalState = 1;
                    }else{
                        ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsIfExtPortIfIndex, "physical_status");
                        ret = ubus_invoke_command("port_config", "port_config_get", 
                                                port_config_get_ret_handler_cb, str);
                        if (ret != 0)
                        {
                            return SNMP_ERR_NOSUCHNAME;
                        }
                        data = atoi(jws_read_buf_str());
                        table_entry->jwsIfExtPortPhysicalState = data;
                    }
                }else{
                    ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsIfExtPortIfIndex, "physical_status");
                    ret = ubus_invoke_command("port_config", "port_config_get", 
                                            port_config_get_ret_handler_cb, str);
                    if (ret != 0)
                    {
                        return SNMP_ERR_NOSUCHNAME;
                    }
                    data = atoi(jws_read_buf_str());
                    table_entry->jwsIfExtPortPhysicalState = data;
                }

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsIfExtPortPhysicalState);
                break;
            case COLUMN_JWSIFEXTPORTFLOWCONTROLMODE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                 if(0 == strcmp(jwsDevBaseInfo.serial_num, "54-10-01-06-01-01-00-00") ||
                   0 == strcmp(jwsDevBaseInfo.serial_num, "54-20-01-06-01-02-00-00") )
                {
                    if(table_entry->jwsIfExtPortIfIndex > jwsDevBaseInfo.port_num)
                    {
                        table_entry->jwsIfExtPortFlowControlMode = 2;
                    }else{
                        ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsIfExtPortIfIndex, "flow_control_mode");
                        ret = ubus_invoke_command("port_config", "port_config_get", 
                                                port_config_get_ret_handler_cb, str);
                        if (ret != 0)
                        {
                            return SNMP_ERR_NOSUCHNAME;
                        }
                        data = atoi(jws_read_buf_str());
                        table_entry->jwsIfExtPortFlowControlMode = data;
                    }
                }else{
                    ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsIfExtPortIfIndex, "flow_control_mode");
                    ret = ubus_invoke_command("port_config", "port_config_get", 
                                            port_config_get_ret_handler_cb, str);
                    if (ret != 0)
                    {
                        return SNMP_ERR_NOSUCHNAME;
                    }
                    data = atoi(jws_read_buf_str());
                    table_entry->jwsIfExtPortFlowControlMode = data;
                }

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsIfExtPortFlowControlMode);
                break;
#if 0
            case COLUMN_JWSIFEXTPORTDOT1DSTATE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsIfExtPortIfIndex, "dot1d_state");
                ret = ubus_invoke_command("port_config", "port_config_get", 
                                        port_config_get_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsIfExtPortDot1dState = data;
                
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsIfExtPortDot1dState);
                break;
#endif
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsIfExtPortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSIFEXTPORTADMINMODE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSIFEXTPORTPHYSICALMODE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSIFEXTPORTFLOWCONTROLMODE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsIfExtPortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            bzero(str, sizeof(str));
    
            switch (table_info->colnum) {
            case COLUMN_JWSIFEXTPORTADMINMODE:
                table_entry->old_jwsIfExtPortAdminMode = table_entry->jwsIfExtPortAdminMode;
                table_entry->jwsIfExtPortAdminMode     = *request->requestvb->val.integer;
                
                snprintf(value, sizeof(value), "%ld", table_entry->jwsIfExtPortAdminMode);
                ubus_set_port_cmd_enc(str, sizeof(str), table_entry->jwsIfExtPortIfIndex, "admin_mode", value);
                ret = ubus_invoke_command("port_config", "port_config_set", 
                                    set_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSIFEXTPORTPHYSICALMODE:
                table_entry->old_jwsIfExtPortPhysicalMode = table_entry->jwsIfExtPortPhysicalMode;
                table_entry->jwsIfExtPortPhysicalMode     = *request->requestvb->val.integer;

                snprintf(value, sizeof(value), "%ld", table_entry->jwsIfExtPortPhysicalMode);
                ubus_set_port_cmd_enc(str, sizeof(str), table_entry->jwsIfExtPortIfIndex, "physical_mode", value);
                ret = ubus_invoke_command("port_config", "port_config_set", 
                                    set_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSIFEXTPORTFLOWCONTROLMODE:
                table_entry->old_jwsIfExtPortFlowControlMode = table_entry->jwsIfExtPortFlowControlMode;
                table_entry->jwsIfExtPortFlowControlMode     = *request->requestvb->val.integer;
                
                snprintf(value, sizeof(value), "%ld", table_entry->jwsIfExtPortFlowControlMode);
                ubus_set_port_cmd_enc(str, sizeof(str), table_entry->jwsIfExtPortIfIndex, "flow_control_mode", value);
                ret = ubus_invoke_command("port_config", "port_config_set", 
                                    set_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsIfExtPortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSIFEXTPORTADMINMODE:
                table_entry->jwsIfExtPortAdminMode     = table_entry->old_jwsIfExtPortAdminMode;
                table_entry->old_jwsIfExtPortAdminMode = 0;
                break;
            case COLUMN_JWSIFEXTPORTPHYSICALMODE:
                table_entry->jwsIfExtPortPhysicalMode     = table_entry->old_jwsIfExtPortPhysicalMode;
                table_entry->old_jwsIfExtPortPhysicalMode = 0;
                break;
            case COLUMN_JWSIFEXTPORTFLOWCONTROLMODE:
                table_entry->jwsIfExtPortFlowControlMode     = table_entry->old_jwsIfExtPortFlowControlMode;
                table_entry->old_jwsIfExtPortFlowControlMode = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
