/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17821 2009-11-11 09:00:00Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "jwsJrppRingTable.h"

#include "jws_ubus_if.h"
#include "stdlib.h"
#include "jws_convert.h"
#include "jwslog.h"

/* create a new row in the (unsorted) table */
struct jwsJrppRingTable_entry *
jwsJrppRingTable_createEntry(
                 long  jwsJrppRingIndex,
                 struct jwsJrppRingTable_entry *table_entry
                );
int jwsJrppRingTable_load(netsnmp_cache *cache, void *magic);
void jwsJrppRingTable_free(netsnmp_cache *cache, void *magic);
void jwsJrppRingTable_removeTable();
/* remove a row from the table */
void
jwsJrppRingTable_removeEntry( struct jwsJrppRingTable_entry *entry );

/** Initializes the jwsJrppRingTable module */
void
init_jwsJrppRingTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_jwsJrppRingTable();
}

//  # Determine the first/last column names

/** Initialize the jwsJrppRingTable table by defining its contents and how it's structured */
void
initialize_table_jwsJrppRingTable(void)
{
    static oid jwsJrppRingTable_oid[] = {1,3,6,1,4,1,33444,2,2,10,2,2};
    size_t jwsJrppRingTable_oid_len   = OID_LENGTH(jwsJrppRingTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    reg = netsnmp_create_handler_registration(
              "jwsJrppRingTable",     jwsJrppRingTable_handler,
              jwsJrppRingTable_oid, jwsJrppRingTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: jwsJrppRingIndex */
                           0);
    table_info->min_column = COLUMN_JWSJRPPRINGINDEX;
    table_info->max_column = COLUMN_JWSJRPPRINGROWSTATUS;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = jwsJrppRingTable_get_first_data_point;
    iinfo->get_next_data_point  = jwsJrppRingTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
        netsnmp_inject_handler( reg,
            netsnmp_get_cache_handler(1,
                    jwsJrppRingTable_load, jwsJrppRingTable_free,
                    jwsJrppRingTable_oid, jwsJrppRingTable_oid_len));
}

    /* Typical data structure for a row entry */
struct jwsJrppRingTable_entry {
    /* Index values */
    //long jwsJrppRingIndex;

    /* Column values */
    long jwsJrppRingIndex;
    long old_jwsJrppRingIndex;
    long jwsJrppRingID;
    long old_jwsJrppRingID;
    long jwsJrppRingEnableStatus;
    long old_jwsJrppRingEnableStatus;
    long jwsJrppRingNodePriority;
    long old_jwsJrppRingNodePriority;
    long jwsJrppRingPrimaryPort;
    long old_jwsJrppRingPrimaryPort;
    long jwsJrppRingSecondaryPort;
    long old_jwsJrppRingSecondaryPort;
    long jwsJrppRingRowStatus;

    /* Illustrate using a simple linked list */
    int   valid;
    struct jwsJrppRingTable_entry *next;
};

struct jwsJrppRingTable_entry  *jwsJrppRingTable_head;

int jwsJrppRingTable_load(netsnmp_cache *cache, void *magic)
{
    int ret;
    int i, ring_num;
    struct jwsJrppRingTable_entry table_entry;

    ret = ubus_invoke_command("ring_config", "ring_config_get", get_ret_handler_cb, 
                                "{\"get_args\":[\"ring_num\"]}");
    if (ret != 0)
    {
        LogWrite(ERROR, "file:%s line:%d func:%s, invoke get_args ring_num failed\n",
                        __FILENAME__, __LINE__, __FUNCTION__);
        return -1;
    }
    ring_num = atoi(jws_read_buf_str());
    if (ring_num == -1)
    {
        LogWrite(ERROR, "file:%s line:%d func:%s, joyware ring protocol disable\n",
                        __FILENAME__, __LINE__, __FUNCTION__);
        return -1;
    }

    jwsJrppRingTable_removeTable();

    for (i = 1; i <= ring_num; i++) {
        table_entry.jwsJrppRingRowStatus = 1;
        jwsJrppRingTable_createEntry(i, &table_entry);
    }

    return 0;
}

void jwsJrppRingTable_free(netsnmp_cache *cache, void *magic)
{
    jwsJrppRingTable_removeTable();
}

/* remove a table */
void jwsJrppRingTable_removeTable( ) {

    struct jwsJrppRingTable_entry *ptr;

    LogWrite(DEBUG, "file:%s line:%d func:%s, remove table\n",
                        __FILENAME__, __LINE__, __FUNCTION__);
    for ( ptr  = jwsJrppRingTable_head; ptr != NULL; ptr = ptr->next ) {
        jwsJrppRingTable_removeEntry( ptr );
    }

}

/* create a new row in the (unsorted) table */
struct jwsJrppRingTable_entry *
jwsJrppRingTable_createEntry(
                 long  jwsJrppRingIndex,
                 struct jwsJrppRingTable_entry *table_entry
                ) {
    struct jwsJrppRingTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct jwsJrppRingTable_entry);
    if (!entry)
        return NULL;

    entry->jwsJrppRingIndex = jwsJrppRingIndex;

    if (NULL != table_entry){
        entry->jwsJrppRingRowStatus = table_entry->jwsJrppRingRowStatus;
    }

    entry->next = jwsJrppRingTable_head;
    jwsJrppRingTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
jwsJrppRingTable_removeEntry( struct jwsJrppRingTable_entry *entry ) {
    struct jwsJrppRingTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = jwsJrppRingTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        jwsJrppRingTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
jwsJrppRingTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = jwsJrppRingTable_head;
    return jwsJrppRingTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
jwsJrppRingTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct jwsJrppRingTable_entry *entry = (struct jwsJrppRingTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->jwsJrppRingIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the jwsJrppRingTable table */
int
jwsJrppRingTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct jwsJrppRingTable_entry          *table_entry;

    struct jwsJrppRingTable_entry          *table_row = NULL;
    int ret;
    char str[100] = {0};
    char value[50];
    unsigned int data;

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsJrppRingTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            bzero(str, sizeof(str));

            switch (table_info->colnum) {
            case COLUMN_JWSJRPPRINGINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsJrppRingIndex);
                break;
            case COLUMN_JWSJRPPRINGID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_cmd_enc(str, sizeof(str), table_entry->jwsJrppRingIndex, "ring_name");
                ret = ubus_invoke_command("ring_config", "ring_config_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsJrppRingID = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsJrppRingID);
                break;
            case COLUMN_JWSJRPPRINGENABLESTATUS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_cmd_enc(str, sizeof(str), table_entry->jwsJrppRingIndex, "admin");
                ret = ubus_invoke_command("ring_config", "ring_config_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsJrppRingEnableStatus = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsJrppRingEnableStatus);
                break;
            case COLUMN_JWSJRPPRINGNODEPRIORITY:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_cmd_enc(str, sizeof(str), table_entry->jwsJrppRingIndex, "priority");
                ret = ubus_invoke_command("ring_config", "ring_config_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsJrppRingNodePriority = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsJrppRingNodePriority);
                break;
            case COLUMN_JWSJRPPRINGPRIMARYPORT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_cmd_enc(str, sizeof(str), table_entry->jwsJrppRingIndex, "primary_port");
                ret = ubus_invoke_command("ring_config", "ring_config_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsJrppRingPrimaryPort = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsJrppRingPrimaryPort);
                break;
            case COLUMN_JWSJRPPRINGSECONDARYPORT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_cmd_enc(str, sizeof(str), table_entry->jwsJrppRingIndex, "secondary_port");
                ret = ubus_invoke_command("ring_config", "ring_config_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsJrppRingSecondaryPort = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsJrppRingSecondaryPort);
                break;
            case COLUMN_JWSJRPPRINGROWSTATUS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsJrppRingRowStatus);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsJrppRingTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSJRPPRINGINDEX:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSJRPPRINGID:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSJRPPRINGENABLESTATUS:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSJRPPRINGNODEPRIORITY:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSJRPPRINGPRIMARYPORT:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSJRPPRINGSECONDARYPORT:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSJRPPRINGROWSTATUS:
                ret = netsnmp_check_vb_rowstatus(request->requestvb,
                         (table_entry ? RS_ACTIVE : RS_NONEXISTENT ));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsJrppRingTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSJRPPRINGROWSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_CREATEANDGO:
                case RS_CREATEANDWAIT:
                    table_row = jwsJrppRingTable_createEntry(
                        *table_info->indexes->val.integer,
                        NULL
                        );

                    snprintf(value, sizeof(value), "%ld", *table_info->indexes->val.integer);
                    
                    ubus_add_cmd_enc(str, sizeof(str), *table_info->indexes->val.integer);
                    ret = ubus_invoke_command("ring_config", "ring_config_set", 
                                            set_ret_handler_cb, str);
                    if (ret != 0) {
                        return SNMP_ERR_NOSUCHNAME;
                    }

                    if (table_row) {
                        netsnmp_insert_iterator_context( request, table_row );
                    } else {
                        netsnmp_set_request_error( reqinfo, request,
                                                   SNMP_ERR_RESOURCEUNAVAILABLE );
                        return SNMP_ERR_NOERROR;
                    }
                }
            }
        }
        break;

    case MODE_SET_FREE:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsJrppRingTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSJRPPRINGROWSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_CREATEANDGO:
                case RS_CREATEANDWAIT:
                    if (table_entry && !table_entry->valid) {
                        jwsJrppRingTable_removeEntry( table_row );
                    }
                }
            }
        }
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsJrppRingTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            bzero(str, sizeof(str));
    
            switch (table_info->colnum) {
            case COLUMN_JWSJRPPRINGINDEX:
                table_entry->old_jwsJrppRingIndex = table_entry->jwsJrppRingIndex;
                table_entry->jwsJrppRingIndex     = *request->requestvb->val.integer;
                break;
            case COLUMN_JWSJRPPRINGID:
                table_entry->old_jwsJrppRingID = table_entry->jwsJrppRingID;
                table_entry->jwsJrppRingID     = *request->requestvb->val.integer;
                
                snprintf(value, sizeof(value), "%ld", table_entry->jwsJrppRingID);
                ubus_set_cmd_enc(str, sizeof(str), table_entry->jwsJrppRingIndex, 
                                "ring_name", value);
                ret = ubus_invoke_command("ring_config", "ring_config_set", 
                                        set_ret_handler_cb, str);
                if (ret != 0) {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSJRPPRINGENABLESTATUS:
                table_entry->old_jwsJrppRingEnableStatus = table_entry->jwsJrppRingEnableStatus;
                table_entry->jwsJrppRingEnableStatus     = *request->requestvb->val.integer;
                
                snprintf(value, sizeof(value), "%ld", table_entry->jwsJrppRingEnableStatus);
                ubus_set_cmd_enc(str, sizeof(str), table_entry->jwsJrppRingIndex, 
                                "admin", value);
                ret = ubus_invoke_command("ring_config", "ring_config_set", 
                                        set_ret_handler_cb, str);
                if (ret != 0) {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSJRPPRINGNODEPRIORITY:
                table_entry->old_jwsJrppRingNodePriority = table_entry->jwsJrppRingNodePriority;
                table_entry->jwsJrppRingNodePriority     = *request->requestvb->val.integer;
                
                snprintf(value, sizeof(value), "%ld", table_entry->jwsJrppRingNodePriority);
                ubus_set_cmd_enc(str, sizeof(str), table_entry->jwsJrppRingIndex, 
                                "priority", value);
                ret = ubus_invoke_command("ring_config", "ring_config_set", 
                                        set_ret_handler_cb, str);
                if (ret != 0) {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSJRPPRINGPRIMARYPORT:
                table_entry->old_jwsJrppRingPrimaryPort = table_entry->jwsJrppRingPrimaryPort;
                table_entry->jwsJrppRingPrimaryPort     = *request->requestvb->val.integer;
                
                snprintf(value, sizeof(value), "%ld", table_entry->jwsJrppRingPrimaryPort);
                ubus_set_cmd_enc(str, sizeof(str), table_entry->jwsJrppRingIndex, 
                                "primary_port", value);
                ret = ubus_invoke_command("ring_config", "ring_config_set", 
                                        set_ret_handler_cb, str);
                if (ret != 0) {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSJRPPRINGSECONDARYPORT:
                table_entry->old_jwsJrppRingSecondaryPort = table_entry->jwsJrppRingSecondaryPort;
                table_entry->jwsJrppRingSecondaryPort     = *request->requestvb->val.integer;
                
                snprintf(value, sizeof(value), "%ld", table_entry->jwsJrppRingSecondaryPort);
                ubus_set_cmd_enc(str, sizeof(str), table_entry->jwsJrppRingIndex, 
                                "secondary_port", value);
                ret = ubus_invoke_command("ring_config", "ring_config_set", 
                                        set_ret_handler_cb, str);
                if (ret != 0) {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            }
        }
        /* Check the internal consistency of an active row */
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsJrppRingTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSJRPPRINGROWSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_ACTIVE:
                case RS_CREATEANDGO:
                    if (0/* XXX */) {
                        netsnmp_set_request_error( reqinfo, request,
                                                   SNMP_ERR_INCONSISTENTVALUE );
                        return SNMP_ERR_NOERROR;
                    }
                }
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsJrppRingTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSJRPPRINGINDEX:
                table_entry->jwsJrppRingIndex     = table_entry->old_jwsJrppRingIndex;
                table_entry->old_jwsJrppRingIndex = 0;
                break;
            case COLUMN_JWSJRPPRINGID:
                table_entry->jwsJrppRingID     = table_entry->old_jwsJrppRingID;
                table_entry->old_jwsJrppRingID = 0;
                break;
            case COLUMN_JWSJRPPRINGENABLESTATUS:
                table_entry->jwsJrppRingEnableStatus     = table_entry->old_jwsJrppRingEnableStatus;
                table_entry->old_jwsJrppRingEnableStatus = 0;
                break;
            case COLUMN_JWSJRPPRINGNODEPRIORITY:
                table_entry->jwsJrppRingNodePriority     = table_entry->old_jwsJrppRingNodePriority;
                table_entry->old_jwsJrppRingNodePriority = 0;
                break;
            case COLUMN_JWSJRPPRINGPRIMARYPORT:
                table_entry->jwsJrppRingPrimaryPort     = table_entry->old_jwsJrppRingPrimaryPort;
                table_entry->old_jwsJrppRingPrimaryPort = 0;
                break;
            case COLUMN_JWSJRPPRINGSECONDARYPORT:
                table_entry->jwsJrppRingSecondaryPort     = table_entry->old_jwsJrppRingSecondaryPort;
                table_entry->old_jwsJrppRingSecondaryPort = 0;
                break;
            case COLUMN_JWSJRPPRINGROWSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_CREATEANDGO:
                case RS_CREATEANDWAIT:
                    if (table_entry && !table_entry->valid) {
                        jwsJrppRingTable_removeEntry( table_row );
                    }
                }
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsJrppRingTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSJRPPRINGROWSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_CREATEANDGO:
                    table_entry->valid = 1;
                    /* Fall-through */
                case RS_ACTIVE:
                    table_entry->jwsJrppRingRowStatus = RS_ACTIVE;
                    break;

                case RS_CREATEANDWAIT:
                    table_entry->valid = 1;
                    /* Fall-through */
                case RS_NOTINSERVICE:
                    table_entry->jwsJrppRingRowStatus = RS_NOTINSERVICE;
                    break;

                case RS_DESTROY:

                    ubus_clear_cmd_enc(str, sizeof(str), *table_info->indexes->val.integer);
                    ret = ubus_invoke_command("ring_config", "ring_config_clear", 
                                            clear_ret_handler_cb, str);
                    if (ret != 0) {
                        return SNMP_ERR_NOSUCHNAME;
                    }

                    //jwsJrppRingTable_removeEntry( table_row );
                }
            }
        }
        break;
    }
    return SNMP_ERR_NOERROR;
}
