/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17821 2009-11-11 09:00:00Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "jwsPriRateLimitTable.h"
#include "stdlib.h"
#include "jws_ubus_if.h"
#include "jwslog.h"
#include "jwsDevBaseInfo.h"

#define PRI_RATE_LIMIT_TYPE_MASK_LEN (1)

/* create a new row in the (unsorted) table */
struct jwsPriRateLimitTable_entry *
jwsPriRateLimitTable_createEntry(
                 long  jwsPriRateLimitPortIndex
                );

/** Initializes the jwsPriRateLimitTable module */
void
init_jwsPriRateLimitTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_jwsPriRateLimitTable();
}

//  # Determine the first/last column names

/** Initialize the jwsPriRateLimitTable table by defining its contents and how it's structured */
void
initialize_table_jwsPriRateLimitTable(void)
{
    static oid jwsPriRateLimitTable_oid[] = {1,3,6,1,4,1,33444,2,2,3,1,1};
    size_t jwsPriRateLimitTable_oid_len   = OID_LENGTH(jwsPriRateLimitTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    int i;
    struct stJwsDevBaseInfo jwsDevBaseInfo;

    reg = netsnmp_create_handler_registration(
              "jwsPriRateLimitTable",     jwsPriRateLimitTable_handler,
              jwsPriRateLimitTable_oid, jwsPriRateLimitTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: jwsPriRateLimitPortIndex */
                           0);
    table_info->min_column = COLUMN_JWSPRIRATELIMITPORTINDEX;
    table_info->max_column = COLUMN_JWSPRIRATELIMITEGRESSRATE;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = jwsPriRateLimitTable_get_first_data_point;
    iinfo->get_next_data_point  = jwsPriRateLimitTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
    getJwsDevBaseInfo(&jwsDevBaseInfo);
    for (i = 1; i <= jwsDevBaseInfo.port_num; i++)
    {
        jwsPriRateLimitTable_createEntry(i);
    }
}

    /* Typical data structure for a row entry */
struct jwsPriRateLimitTable_entry {
    /* Index values */
//    long jwsPriRateLimitPortIndex;

    /* Column values */
    long jwsPriRateLimitPortIndex;
    long jwsPriRateLimitIngressBucket0Enable;
    long old_jwsPriRateLimitIngressBucket0Enable;
    char jwsPriRateLimitIngressBucket0TypeMask[PRI_RATE_LIMIT_TYPE_MASK_LEN];
    size_t jwsPriRateLimitIngressBucket0TypeMask_len;
    char old_jwsPriRateLimitIngressBucket0TypeMask[PRI_RATE_LIMIT_TYPE_MASK_LEN];
    size_t old_jwsPriRateLimitIngressBucket0TypeMask_len;
    long jwsPriRateLimitIngressBucket0Rate;
    long old_jwsPriRateLimitIngressBucket0Rate;
    long jwsPriRateLimitIngressBucket1Enable;
    long old_jwsPriRateLimitIngressBucket1Enable;
    char jwsPriRateLimitIngressBucket1TypeMask[PRI_RATE_LIMIT_TYPE_MASK_LEN];
    size_t jwsPriRateLimitIngressBucket1TypeMask_len;
    char old_jwsPriRateLimitIngressBucket1TypeMask[PRI_RATE_LIMIT_TYPE_MASK_LEN];
    size_t old_jwsPriRateLimitIngressBucket1TypeMask_len;
    long jwsPriRateLimitIngressBucket1Rate;
    long old_jwsPriRateLimitIngressBucket1Rate;
    long jwsPriRateLimitIngressBucket2Enable;
    long old_jwsPriRateLimitIngressBucket2Enable;
    char jwsPriRateLimitIngressBucket2TypeMask[PRI_RATE_LIMIT_TYPE_MASK_LEN];
    size_t jwsPriRateLimitIngressBucket2TypeMask_len;
    char old_jwsPriRateLimitIngressBucket2TypeMask[PRI_RATE_LIMIT_TYPE_MASK_LEN];
    size_t old_jwsPriRateLimitIngressBucket2TypeMask_len;
    long jwsPriRateLimitIngressBucket2Rate;
    long old_jwsPriRateLimitIngressBucket2Rate;
    long jwsPriRateLimitIngressBucket3Enable;
    long old_jwsPriRateLimitIngressBucket3Enable;
    char jwsPriRateLimitIngressBucket3TypeMask[PRI_RATE_LIMIT_TYPE_MASK_LEN];
    size_t jwsPriRateLimitIngressBucket3TypeMask_len;
    char old_jwsPriRateLimitIngressBucket3TypeMask[PRI_RATE_LIMIT_TYPE_MASK_LEN];
    size_t old_jwsPriRateLimitIngressBucket3TypeMask_len;
    long jwsPriRateLimitIngressBucket3Rate;
    long old_jwsPriRateLimitIngressBucket3Rate;
    long jwsPriRateLimitIngressBucket4Enable;
    long old_jwsPriRateLimitIngressBucket4Enable;
    char jwsPriRateLimitIngressBucket4TypeMask[PRI_RATE_LIMIT_TYPE_MASK_LEN];
    size_t jwsPriRateLimitIngressBucket4TypeMask_len;
    char old_jwsPriRateLimitIngressBucket4TypeMask[PRI_RATE_LIMIT_TYPE_MASK_LEN];
    size_t old_jwsPriRateLimitIngressBucket4TypeMask_len;
    long jwsPriRateLimitIngressBucket4Rate;
    long old_jwsPriRateLimitIngressBucket4Rate;
    long jwsPriRateLimitEgressRateEnable;
    long old_jwsPriRateLimitEgressRateEnable;
    long jwsPriRateLimitEgressRate;
    long old_jwsPriRateLimitEgressRate;

    /* Illustrate using a simple linked list */
    int   valid;
    struct jwsPriRateLimitTable_entry *next;
};

struct jwsPriRateLimitTable_entry  *jwsPriRateLimitTable_head;

/* create a new row in the (unsorted) table */
struct jwsPriRateLimitTable_entry *
jwsPriRateLimitTable_createEntry(
                 long  jwsPriRateLimitPortIndex
                ) {
    struct jwsPriRateLimitTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct jwsPriRateLimitTable_entry);
    if (!entry)
        return NULL;

    entry->jwsPriRateLimitPortIndex = jwsPriRateLimitPortIndex;
    entry->next = jwsPriRateLimitTable_head;
    jwsPriRateLimitTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
jwsPriRateLimitTable_removeEntry( struct jwsPriRateLimitTable_entry *entry ) {
    struct jwsPriRateLimitTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = jwsPriRateLimitTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        jwsPriRateLimitTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
jwsPriRateLimitTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = jwsPriRateLimitTable_head;
    return jwsPriRateLimitTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
jwsPriRateLimitTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct jwsPriRateLimitTable_entry *entry = (struct jwsPriRateLimitTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->jwsPriRateLimitPortIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the jwsPriRateLimitTable table */
int
jwsPriRateLimitTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct jwsPriRateLimitTable_entry          *table_entry;

    int ret = SNMP_ERR_NOERROR;
    int i;
    signed int data = 0;
    char str[100] = {0};
    char value[10] = {0};
    unsigned char tmpdata = 0, tmpdata1 = 0;

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsPriRateLimitTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            bzero(str, sizeof(str));
            tmpdata = 0;
    
            switch (table_info->colnum) {
            case COLUMN_JWSPRIRATELIMITPORTINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsPriRateLimitPortIndex);
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET0ENABLE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "ingress_bucket0_enable");
                ret = ubus_invoke_command("rate_limit", "rate_limit_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsPriRateLimitIngressBucket0Enable = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsPriRateLimitIngressBucket0Enable);
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET0TYPEMASK:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "ingress_bucket0_type_mask");
                ret = ubus_invoke_command("rate_limit", "rate_limit_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                for(i=0; i<=7; i++){
                    if((data >> i) & 0x01){
                        tmpdata |= (0x01 << (7-i));
                    }
                }

                memcpy(table_entry->jwsPriRateLimitIngressBucket0TypeMask, (char *)&tmpdata, 1);
                table_entry->jwsPriRateLimitIngressBucket0TypeMask_len = 1;

#if 0
                ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, 
                                "ingress_bucket0_type_mask");
                ret = ubus_invoke_command("rate_limit", "rate_limit_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                table_entry->jwsPriRateLimitIngressBucket0TypeMask_len = count_char(jws_read_buf_str(), '-') + 1;
                convert_str2array(jws_read_buf_str(), 
                    table_entry->jwsPriRateLimitIngressBucket0TypeMask, 
                    table_entry->jwsPriRateLimitIngressBucket0TypeMask_len);
#endif

                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*) table_entry->jwsPriRateLimitIngressBucket0TypeMask,
                                          table_entry->jwsPriRateLimitIngressBucket0TypeMask_len );
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET0RATE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "ingress_bucket0_rate");
                ret = ubus_invoke_command("rate_limit", "rate_limit_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsPriRateLimitIngressBucket0Rate = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsPriRateLimitIngressBucket0Rate);
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET1ENABLE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "ingress_bucket1_enable");
                ret = ubus_invoke_command("rate_limit", "rate_limit_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsPriRateLimitIngressBucket1Enable = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsPriRateLimitIngressBucket1Enable);
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET1TYPEMASK:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "ingress_bucket1_type_mask");
                ret = ubus_invoke_command("rate_limit", "rate_limit_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                for(i=0; i<=7; i++){
                    if((data >> i) & 0x01){
                        tmpdata |= (0x01 << (7-i));
                    }
                }

                memcpy(table_entry->jwsPriRateLimitIngressBucket1TypeMask, (char *)&tmpdata, 1);
                table_entry->jwsPriRateLimitIngressBucket1TypeMask_len = 1;
#if 0
                ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, 
                                "ingress_bucket1_type_mask");
                ret = ubus_invoke_command("rate_limit", "rate_limit_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                table_entry->jwsPriRateLimitIngressBucket1TypeMask_len = count_char(jws_read_buf_str(), '-') + 1;
                convert_str2array(jws_read_buf_str(), 
                    table_entry->jwsPriRateLimitIngressBucket1TypeMask, 
                    table_entry->jwsPriRateLimitIngressBucket1TypeMask_len);
#endif
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->jwsPriRateLimitIngressBucket1TypeMask,
                                          table_entry->jwsPriRateLimitIngressBucket1TypeMask_len);
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET1RATE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "ingress_bucket1_rate");
                ret = ubus_invoke_command("rate_limit", "rate_limit_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsPriRateLimitIngressBucket1Rate = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsPriRateLimitIngressBucket1Rate);
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET2ENABLE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "ingress_bucket2_enable");
                ret = ubus_invoke_command("rate_limit", "rate_limit_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsPriRateLimitIngressBucket2Enable = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsPriRateLimitIngressBucket2Enable);
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET2TYPEMASK:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "ingress_bucket2_type_mask");
                ret = ubus_invoke_command("rate_limit", "rate_limit_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                for(i=0; i<=7; i++){
                    if((data >> i) & 0x01){
                        tmpdata |= (0x01 << (7-i));
                    }
                }

                memcpy(table_entry->jwsPriRateLimitIngressBucket2TypeMask, (char *)&tmpdata, 1);
                table_entry->jwsPriRateLimitIngressBucket2TypeMask_len = 1;

#if 0
                ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, 
                                "ingress_bucket2_type_mask");
                ret = ubus_invoke_command("rate_limit", "rate_limit_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                table_entry->jwsPriRateLimitIngressBucket2TypeMask_len = count_char(jws_read_buf_str(), '-') + 1;
                convert_str2array(jws_read_buf_str(), 
                    table_entry->jwsPriRateLimitIngressBucket2TypeMask, 
                    table_entry->jwsPriRateLimitIngressBucket2TypeMask_len);
#endif
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->jwsPriRateLimitIngressBucket2TypeMask,
                                          table_entry->jwsPriRateLimitIngressBucket2TypeMask_len);
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET2RATE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "ingress_bucket2_rate");
                ret = ubus_invoke_command("rate_limit", "rate_limit_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsPriRateLimitIngressBucket2Rate = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsPriRateLimitIngressBucket2Rate);
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET3ENABLE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "ingress_bucket3_enable");
                ret = ubus_invoke_command("rate_limit", "rate_limit_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsPriRateLimitIngressBucket3Enable = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsPriRateLimitIngressBucket3Enable);
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET3TYPEMASK:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "ingress_bucket3_type_mask");
                ret = ubus_invoke_command("rate_limit", "rate_limit_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                for(i=0; i<=7; i++){
                    if((data >> i) & 0x01){
                        tmpdata |= (0x01 << (7-i));
                    }
                }

                memcpy(table_entry->jwsPriRateLimitIngressBucket3TypeMask, (char *)&tmpdata, 1);
                table_entry->jwsPriRateLimitIngressBucket3TypeMask_len = 1;

#if 0
                ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, 
                                "ingress_bucket3_type_mask");
                ret = ubus_invoke_command("rate_limit", "rate_limit_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                table_entry->jwsPriRateLimitIngressBucket3TypeMask_len = count_char(jws_read_buf_str(), '-') + 1;
                convert_str2array(jws_read_buf_str(), 
                    table_entry->jwsPriRateLimitIngressBucket3TypeMask, 
                    table_entry->jwsPriRateLimitIngressBucket3TypeMask_len);
#endif
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->jwsPriRateLimitIngressBucket3TypeMask,
                                          table_entry->jwsPriRateLimitIngressBucket3TypeMask_len);
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET3RATE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "ingress_bucket3_rate");
                ret = ubus_invoke_command("rate_limit", "rate_limit_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsPriRateLimitIngressBucket3Rate = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsPriRateLimitIngressBucket3Rate);
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET4ENABLE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "ingress_bucket4_enable");
                ret = ubus_invoke_command("rate_limit", "rate_limit_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsPriRateLimitIngressBucket4Enable = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsPriRateLimitIngressBucket4Enable);
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET4TYPEMASK:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "ingress_bucket4_type_mask");
                ret = ubus_invoke_command("rate_limit", "rate_limit_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                for(i=0; i<=7; i++){
                    if((data >> i) & 0x01){
                        tmpdata |= (0x01 << (7-i));
                    }
                }
                memcpy(table_entry->jwsPriRateLimitIngressBucket4TypeMask, (char *)&tmpdata, 1);
                table_entry->jwsPriRateLimitIngressBucket4TypeMask_len = 1;

#if 0
                ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, 
                                "ingress_bucket4_type_mask");
                ret = ubus_invoke_command("rate_limit", "rate_limit_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                table_entry->jwsPriRateLimitIngressBucket4TypeMask_len = count_char(jws_read_buf_str(), '-') + 1;
                convert_str2array(jws_read_buf_str(), 
                    table_entry->jwsPriRateLimitIngressBucket4TypeMask, 
                    table_entry->jwsPriRateLimitIngressBucket4TypeMask_len);
#endif
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->jwsPriRateLimitIngressBucket4TypeMask,
                                          table_entry->jwsPriRateLimitIngressBucket4TypeMask_len);
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET4RATE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "ingress_bucket4_rate");
                ret = ubus_invoke_command("rate_limit", "rate_limit_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsPriRateLimitIngressBucket4Rate = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsPriRateLimitIngressBucket4Rate);
                break;
            case COLUMN_JWSPRIRATELIMITEGRESSRATEENABLE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "egress_rate_enable");
                ret = ubus_invoke_command("rate_limit", "rate_limit_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsPriRateLimitEgressRateEnable = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsPriRateLimitEgressRateEnable);
                break;
            case COLUMN_JWSPRIRATELIMITEGRESSRATE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "egress_rate");
                ret = ubus_invoke_command("rate_limit", "rate_limit_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsPriRateLimitEgressRate = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsPriRateLimitEgressRate);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsPriRateLimitTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET0ENABLE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET0TYPEMASK:
	        /* or possiblc 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->jwsPriRateLimitIngressBucket0TypeMask));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET0RATE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET1ENABLE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET1TYPEMASK:
	        /* or possiblc 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->jwsPriRateLimitIngressBucket1TypeMask));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET1RATE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET2ENABLE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET2TYPEMASK:
	        /* or possiblc 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->jwsPriRateLimitIngressBucket2TypeMask));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET2RATE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET3ENABLE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET3TYPEMASK:
	        /* or possiblc 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->jwsPriRateLimitIngressBucket3TypeMask));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET3RATE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET4ENABLE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET4TYPEMASK:
	        /* or possiblc 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->jwsPriRateLimitIngressBucket4TypeMask));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET4RATE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSPRIRATELIMITEGRESSRATEENABLE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSPRIRATELIMITEGRESSRATE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsPriRateLimitTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            bzero(str, sizeof(str));
            tmpdata = 0;
    
            switch (table_info->colnum) {
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET0ENABLE:
                table_entry->old_jwsPriRateLimitIngressBucket0Enable = table_entry->jwsPriRateLimitIngressBucket0Enable;
                table_entry->jwsPriRateLimitIngressBucket0Enable     = *request->requestvb->val.integer;

                snprintf(value, sizeof(value), "%ld", table_entry->jwsPriRateLimitIngressBucket0Enable);
                ubus_set_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "ingress_bucket0_enable", value);
                ret = ubus_invoke_command("rate_limit", "rate_limit_set", 
                                    set_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET0TYPEMASK:
                memcpy( table_entry->old_jwsPriRateLimitIngressBucket0TypeMask,
                        table_entry->jwsPriRateLimitIngressBucket0TypeMask,
                        sizeof(table_entry->jwsPriRateLimitIngressBucket0TypeMask));
                table_entry->old_jwsPriRateLimitIngressBucket0TypeMask_len =
                        table_entry->jwsPriRateLimitIngressBucket0TypeMask_len;
                memset( table_entry->jwsPriRateLimitIngressBucket0TypeMask, 0,
                        sizeof(table_entry->jwsPriRateLimitIngressBucket0TypeMask));
                memcpy( table_entry->jwsPriRateLimitIngressBucket0TypeMask,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->jwsPriRateLimitIngressBucket0TypeMask_len =
                        request->requestvb->val_len;

                memcpy((char *)&tmpdata1, table_entry->jwsPriRateLimitIngressBucket0TypeMask, 1);
                for(i=0; i<=7; i++){
                    if((tmpdata1 >> i) & 0x01){
                        tmpdata |= (0x01 << (7-i));
                    }
                }

                snprintf(value, sizeof(value), "%d", tmpdata);
                ubus_set_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, 
                                "ingress_bucket0_type_mask", value);
                ret = ubus_invoke_command("rate_limit", "rate_limit_set", 
                                        set_ret_handler_cb, str);
                if (ret != 0) {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET0RATE:
                table_entry->old_jwsPriRateLimitIngressBucket0Rate = table_entry->jwsPriRateLimitIngressBucket0Rate;
                table_entry->jwsPriRateLimitIngressBucket0Rate     = *request->requestvb->val.integer;
                
                snprintf(value, sizeof(value), "%ld", table_entry->jwsPriRateLimitIngressBucket0Rate);
                ubus_set_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "ingress_bucket0_rate", value);
                ret = ubus_invoke_command("rate_limit", "rate_limit_set", 
                                    set_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET1ENABLE:
                table_entry->old_jwsPriRateLimitIngressBucket1Enable = table_entry->jwsPriRateLimitIngressBucket1Enable;
                table_entry->jwsPriRateLimitIngressBucket1Enable     = *request->requestvb->val.integer;

                snprintf(value, sizeof(value), "%ld", table_entry->jwsPriRateLimitIngressBucket1Enable);
                ubus_set_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "ingress_bucket1_enable", value);
                ret = ubus_invoke_command("rate_limit", "rate_limit_set", 
                                    set_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET1TYPEMASK:
                memcpy( table_entry->old_jwsPriRateLimitIngressBucket1TypeMask,
                        table_entry->jwsPriRateLimitIngressBucket1TypeMask,
                        sizeof(table_entry->jwsPriRateLimitIngressBucket1TypeMask));
                table_entry->old_jwsPriRateLimitIngressBucket1TypeMask_len =
                        table_entry->jwsPriRateLimitIngressBucket1TypeMask_len;
                memset( table_entry->jwsPriRateLimitIngressBucket1TypeMask, 0,
                        sizeof(table_entry->jwsPriRateLimitIngressBucket1TypeMask));
                memcpy( table_entry->jwsPriRateLimitIngressBucket1TypeMask,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->jwsPriRateLimitIngressBucket1TypeMask_len =
                        request->requestvb->val_len;

                memcpy((char *)&tmpdata1, table_entry->jwsPriRateLimitIngressBucket1TypeMask, 1);
                for(i=0; i<=7; i++){
                    if((tmpdata1 >> i) & 0x01){
                        tmpdata |= (0x01 << (7-i));
                    }
                }

                snprintf(value, sizeof(value), "%d", tmpdata);
                ubus_set_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, 
                                "ingress_bucket1_type_mask", value);
                ret = ubus_invoke_command("rate_limit", "rate_limit_set", 
                                        set_ret_handler_cb, str);
                if (ret != 0) {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET1RATE:
                table_entry->old_jwsPriRateLimitIngressBucket1Rate = table_entry->jwsPriRateLimitIngressBucket1Rate;
                table_entry->jwsPriRateLimitIngressBucket1Rate     = *request->requestvb->val.integer;
                
                snprintf(value, sizeof(value), "%ld", table_entry->jwsPriRateLimitIngressBucket1Rate);
                ubus_set_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "ingress_bucket1_rate", value);
                ret = ubus_invoke_command("rate_limit", "rate_limit_set", 
                                    set_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET2ENABLE:
                table_entry->old_jwsPriRateLimitIngressBucket2Enable = table_entry->jwsPriRateLimitIngressBucket2Enable;
                table_entry->jwsPriRateLimitIngressBucket2Enable     = *request->requestvb->val.integer;

                snprintf(value, sizeof(value), "%ld", table_entry->jwsPriRateLimitIngressBucket2Enable);
                ubus_set_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "ingress_bucket2_enable", value);
                ret = ubus_invoke_command("rate_limit", "rate_limit_set", 
                                    set_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET2TYPEMASK:
                memcpy( table_entry->old_jwsPriRateLimitIngressBucket2TypeMask,
                        table_entry->jwsPriRateLimitIngressBucket2TypeMask,
                        sizeof(table_entry->jwsPriRateLimitIngressBucket2TypeMask));
                table_entry->old_jwsPriRateLimitIngressBucket2TypeMask_len =
                        table_entry->jwsPriRateLimitIngressBucket2TypeMask_len;
                memset( table_entry->jwsPriRateLimitIngressBucket2TypeMask, 0,
                        sizeof(table_entry->jwsPriRateLimitIngressBucket2TypeMask));
                memcpy( table_entry->jwsPriRateLimitIngressBucket2TypeMask,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->jwsPriRateLimitIngressBucket2TypeMask_len =
                        request->requestvb->val_len;

                memcpy((char *)&tmpdata1, table_entry->jwsPriRateLimitIngressBucket2TypeMask, 1);
                for(i=0; i<=7; i++){
                    if((tmpdata1 >> i) & 0x01){
                        tmpdata |= (0x01 << (7-i));
                    }
                }

                snprintf(value, sizeof(value), "%d", tmpdata);
                ubus_set_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, 
                                "ingress_bucket2_type_mask", value);
                ret = ubus_invoke_command("rate_limit", "rate_limit_set", 
                                        set_ret_handler_cb, str);
                if (ret != 0) {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET2RATE:
                table_entry->old_jwsPriRateLimitIngressBucket2Rate = table_entry->jwsPriRateLimitIngressBucket2Rate;
                table_entry->jwsPriRateLimitIngressBucket2Rate     = *request->requestvb->val.integer;
                
                snprintf(value, sizeof(value), "%ld", table_entry->jwsPriRateLimitIngressBucket2Rate);
                ubus_set_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "ingress_bucket2_rate", value);
                ret = ubus_invoke_command("rate_limit", "rate_limit_set", 
                                    set_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET3ENABLE:
                table_entry->old_jwsPriRateLimitIngressBucket3Enable = table_entry->jwsPriRateLimitIngressBucket3Enable;
                table_entry->jwsPriRateLimitIngressBucket3Enable     = *request->requestvb->val.integer;

                snprintf(value, sizeof(value), "%ld", table_entry->jwsPriRateLimitIngressBucket3Enable);
                ubus_set_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "ingress_bucket3_enable", value);
                ret = ubus_invoke_command("rate_limit", "rate_limit_set", 
                                    set_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET3TYPEMASK:
                memcpy( table_entry->old_jwsPriRateLimitIngressBucket3TypeMask,
                        table_entry->jwsPriRateLimitIngressBucket3TypeMask,
                        sizeof(table_entry->jwsPriRateLimitIngressBucket3TypeMask));
                table_entry->old_jwsPriRateLimitIngressBucket3TypeMask_len =
                        table_entry->jwsPriRateLimitIngressBucket3TypeMask_len;
                memset( table_entry->jwsPriRateLimitIngressBucket3TypeMask, 0,
                        sizeof(table_entry->jwsPriRateLimitIngressBucket3TypeMask));
                memcpy( table_entry->jwsPriRateLimitIngressBucket3TypeMask,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->jwsPriRateLimitIngressBucket3TypeMask_len =
                        request->requestvb->val_len;

                memcpy((char *)&tmpdata1, table_entry->jwsPriRateLimitIngressBucket3TypeMask, 1);
                for(i=0; i<=7; i++){
                    if((tmpdata1 >> i) & 0x01){
                        tmpdata |= (0x01 << (7-i));
                    }
                }

                snprintf(value, sizeof(value), "%d", tmpdata);
                ubus_set_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, 
                                "ingress_bucket3_type_mask", value);
                ret = ubus_invoke_command("rate_limit", "rate_limit_set", 
                                        set_ret_handler_cb, str);
                if (ret != 0) {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET3RATE:
                table_entry->old_jwsPriRateLimitIngressBucket3Rate = table_entry->jwsPriRateLimitIngressBucket3Rate;
                table_entry->jwsPriRateLimitIngressBucket3Rate     = *request->requestvb->val.integer;
                
                snprintf(value, sizeof(value), "%ld", table_entry->jwsPriRateLimitIngressBucket3Rate);
                ubus_set_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "ingress_bucket3_rate", value);
                ret = ubus_invoke_command("rate_limit", "rate_limit_set", 
                                    set_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET4ENABLE:
                table_entry->old_jwsPriRateLimitIngressBucket4Enable = table_entry->jwsPriRateLimitIngressBucket4Enable;
                table_entry->jwsPriRateLimitIngressBucket4Enable     = *request->requestvb->val.integer;
                
                snprintf(value, sizeof(value), "%ld", table_entry->jwsPriRateLimitIngressBucket4Enable);
                ubus_set_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "ingress_bucket4_enable", value);
                ret = ubus_invoke_command("rate_limit", "rate_limit_set", 
                                    set_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET4TYPEMASK:
                memcpy( table_entry->old_jwsPriRateLimitIngressBucket4TypeMask,
                        table_entry->jwsPriRateLimitIngressBucket4TypeMask,
                        sizeof(table_entry->jwsPriRateLimitIngressBucket4TypeMask));
                table_entry->old_jwsPriRateLimitIngressBucket4TypeMask_len =
                        table_entry->jwsPriRateLimitIngressBucket4TypeMask_len;
                memset( table_entry->jwsPriRateLimitIngressBucket4TypeMask, 0,
                        sizeof(table_entry->jwsPriRateLimitIngressBucket4TypeMask));
                memcpy( table_entry->jwsPriRateLimitIngressBucket4TypeMask,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->jwsPriRateLimitIngressBucket4TypeMask_len =
                        request->requestvb->val_len;

                memcpy((char *)&tmpdata1, table_entry->jwsPriRateLimitIngressBucket4TypeMask, 1);
                for(i=0; i<=7; i++){
                    if((tmpdata1 >> i) & 0x01){
                        tmpdata |= (0x01 << (7-i));
                    }
                }

                snprintf(value, sizeof(value), "%d", tmpdata);
                ubus_set_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, 
                                "ingress_bucket4_type_mask", value);
                ret = ubus_invoke_command("rate_limit", "rate_limit_set", 
                                        set_ret_handler_cb, str);
                if (ret != 0) {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET4RATE:
                table_entry->old_jwsPriRateLimitIngressBucket4Rate = table_entry->jwsPriRateLimitIngressBucket4Rate;
                table_entry->jwsPriRateLimitIngressBucket4Rate     = *request->requestvb->val.integer;
                
                snprintf(value, sizeof(value), "%ld", table_entry->jwsPriRateLimitIngressBucket4Rate);
                ubus_set_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "ingress_bucket4_rate", value);
                ret = ubus_invoke_command("rate_limit", "rate_limit_set", 
                                    set_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSPRIRATELIMITEGRESSRATEENABLE:
                table_entry->old_jwsPriRateLimitEgressRateEnable = table_entry->jwsPriRateLimitEgressRateEnable;
                table_entry->jwsPriRateLimitEgressRateEnable     = *request->requestvb->val.integer;
                
                snprintf(value, sizeof(value), "%ld", table_entry->jwsPriRateLimitEgressRateEnable);
                ubus_set_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "egress_rate_enable", value);
                ret = ubus_invoke_command("rate_limit", "rate_limit_set", 
                                    set_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSPRIRATELIMITEGRESSRATE:
                table_entry->old_jwsPriRateLimitEgressRate = table_entry->jwsPriRateLimitEgressRate;
                table_entry->jwsPriRateLimitEgressRate     = *request->requestvb->val.integer;

                snprintf(value, sizeof(value), "%ld", table_entry->jwsPriRateLimitEgressRate);
                ubus_set_port_cmd_enc(str, sizeof(str), table_entry->jwsPriRateLimitPortIndex, "egress_rate", value);
                ret = ubus_invoke_command("rate_limit", "rate_limit_set", 
                                    set_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsPriRateLimitTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET0ENABLE:
                table_entry->jwsPriRateLimitIngressBucket0Enable     = table_entry->old_jwsPriRateLimitIngressBucket0Enable;
                table_entry->old_jwsPriRateLimitIngressBucket0Enable = 0;
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET0TYPEMASK:
                memcpy( table_entry->jwsPriRateLimitIngressBucket0TypeMask,
                        table_entry->old_jwsPriRateLimitIngressBucket0TypeMask,
                        sizeof(table_entry->jwsPriRateLimitIngressBucket0TypeMask));
                memset( table_entry->old_jwsPriRateLimitIngressBucket0TypeMask, 0,
                        sizeof(table_entry->jwsPriRateLimitIngressBucket0TypeMask));
                table_entry->jwsPriRateLimitIngressBucket0TypeMask_len =
                        table_entry->old_jwsPriRateLimitIngressBucket0TypeMask_len;
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET0RATE:
                table_entry->jwsPriRateLimitIngressBucket0Rate     = table_entry->old_jwsPriRateLimitIngressBucket0Rate;
                table_entry->old_jwsPriRateLimitIngressBucket0Rate = 0;
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET1ENABLE:
                table_entry->jwsPriRateLimitIngressBucket1Enable     = table_entry->old_jwsPriRateLimitIngressBucket1Enable;
                table_entry->old_jwsPriRateLimitIngressBucket1Enable = 0;
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET1TYPEMASK:
                memcpy( table_entry->jwsPriRateLimitIngressBucket1TypeMask,
                        table_entry->old_jwsPriRateLimitIngressBucket1TypeMask,
                        sizeof(table_entry->jwsPriRateLimitIngressBucket1TypeMask));
                memset( table_entry->old_jwsPriRateLimitIngressBucket1TypeMask, 0,
                        sizeof(table_entry->jwsPriRateLimitIngressBucket1TypeMask));
                table_entry->jwsPriRateLimitIngressBucket1TypeMask_len =
                        table_entry->old_jwsPriRateLimitIngressBucket1TypeMask_len;
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET1RATE:
                table_entry->jwsPriRateLimitIngressBucket1Rate     = table_entry->old_jwsPriRateLimitIngressBucket1Rate;
                table_entry->old_jwsPriRateLimitIngressBucket1Rate = 0;
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET2ENABLE:
                table_entry->jwsPriRateLimitIngressBucket2Enable     = table_entry->old_jwsPriRateLimitIngressBucket2Enable;
                table_entry->old_jwsPriRateLimitIngressBucket2Enable = 0;
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET2TYPEMASK:
                memcpy( table_entry->jwsPriRateLimitIngressBucket2TypeMask,
                        table_entry->old_jwsPriRateLimitIngressBucket2TypeMask,
                        sizeof(table_entry->jwsPriRateLimitIngressBucket2TypeMask));
                memset( table_entry->old_jwsPriRateLimitIngressBucket2TypeMask, 0,
                        sizeof(table_entry->jwsPriRateLimitIngressBucket2TypeMask));
                table_entry->jwsPriRateLimitIngressBucket2TypeMask_len =
                        table_entry->old_jwsPriRateLimitIngressBucket2TypeMask_len;
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET2RATE:
                table_entry->jwsPriRateLimitIngressBucket2Rate     = table_entry->old_jwsPriRateLimitIngressBucket2Rate;
                table_entry->old_jwsPriRateLimitIngressBucket2Rate = 0;
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET3ENABLE:
                table_entry->jwsPriRateLimitIngressBucket3Enable     = table_entry->old_jwsPriRateLimitIngressBucket3Enable;
                table_entry->old_jwsPriRateLimitIngressBucket3Enable = 0;
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET3TYPEMASK:
                memcpy( table_entry->jwsPriRateLimitIngressBucket3TypeMask,
                        table_entry->old_jwsPriRateLimitIngressBucket3TypeMask,
                        sizeof(table_entry->jwsPriRateLimitIngressBucket3TypeMask));
                memset( table_entry->old_jwsPriRateLimitIngressBucket3TypeMask, 0,
                        sizeof(table_entry->jwsPriRateLimitIngressBucket3TypeMask));
                table_entry->jwsPriRateLimitIngressBucket3TypeMask_len =
                        table_entry->old_jwsPriRateLimitIngressBucket3TypeMask_len;
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET3RATE:
                table_entry->jwsPriRateLimitIngressBucket3Rate     = table_entry->old_jwsPriRateLimitIngressBucket3Rate;
                table_entry->old_jwsPriRateLimitIngressBucket3Rate = 0;
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET4ENABLE:
                table_entry->jwsPriRateLimitIngressBucket4Enable     = table_entry->old_jwsPriRateLimitIngressBucket4Enable;
                table_entry->old_jwsPriRateLimitIngressBucket4Enable = 0;
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET4TYPEMASK:
                memcpy( table_entry->jwsPriRateLimitIngressBucket4TypeMask,
                        table_entry->old_jwsPriRateLimitIngressBucket4TypeMask,
                        sizeof(table_entry->jwsPriRateLimitIngressBucket4TypeMask));
                memset( table_entry->old_jwsPriRateLimitIngressBucket4TypeMask, 0,
                        sizeof(table_entry->jwsPriRateLimitIngressBucket4TypeMask));
                table_entry->jwsPriRateLimitIngressBucket4TypeMask_len =
                        table_entry->old_jwsPriRateLimitIngressBucket4TypeMask_len;
                break;
            case COLUMN_JWSPRIRATELIMITINGRESSBUCKET4RATE:
                table_entry->jwsPriRateLimitIngressBucket4Rate     = table_entry->old_jwsPriRateLimitIngressBucket4Rate;
                table_entry->old_jwsPriRateLimitIngressBucket4Rate = 0;
                break;
            case COLUMN_JWSPRIRATELIMITEGRESSRATEENABLE:
                table_entry->jwsPriRateLimitEgressRateEnable     = table_entry->old_jwsPriRateLimitEgressRateEnable;
                table_entry->old_jwsPriRateLimitEgressRateEnable = 0;
                break;
            case COLUMN_JWSPRIRATELIMITEGRESSRATE:
                table_entry->jwsPriRateLimitEgressRate     = table_entry->old_jwsPriRateLimitEgressRate;
                table_entry->old_jwsPriRateLimitEgressRate = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
