/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17821 2009-11-11 09:00:00Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "jwsQosConfigGroup.h"

#include "jws_ubus_if.h"
#include "stdlib.h"
#include "jwsDevBaseInfo.h"

/* create a new row in the (unsorted) table */
struct jwsQosPortConfigTable_entry *
jwsQosPortConfigTable_createEntry(
                 long  jwsQosPortIndex
                );
struct jwsQosPriority8021pTable_entry *
jwsQosPriority8021pTable_createEntry(
                 long  jwsQos8021pPriorityIndex
                );
struct jwsQosPriorityDscpTable_entry *
jwsQosPriorityDscpTable_createEntry(
                 long  jwsQosDscpPriorityIndex
                );

/** Initializes the jwsQosConfigGroup module */
void
init_jwsQosConfigGroup(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_jwsQosPortConfigTable();
    initialize_table_jwsQosPriority8021pTable();
    initialize_table_jwsQosPriorityDscpTable();
}

//  # Determine the first/last column names

/** Initialize the jwsQosPortConfigTable table by defining its contents and how it's structured */
void
initialize_table_jwsQosPortConfigTable(void)
{
    static oid jwsQosPortConfigTable_oid[] = {1,3,6,1,4,1,33444,2,2,5,1,1};
    size_t jwsQosPortConfigTable_oid_len   = OID_LENGTH(jwsQosPortConfigTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    int i;
    struct stJwsDevBaseInfo jwsDevBaseInfo;

    reg = netsnmp_create_handler_registration(
              "jwsQosPortConfigTable",     jwsQosPortConfigTable_handler,
              jwsQosPortConfigTable_oid, jwsQosPortConfigTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: jwsQosPortIndex */
                           0);
    table_info->min_column = COLUMN_JWSQOSPORTINDEX;
    table_info->max_column = COLUMN_JWSQOSPORTSCHEDULINGMODE;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = jwsQosPortConfigTable_get_first_data_point;
    iinfo->get_next_data_point  = jwsQosPortConfigTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
    getJwsDevBaseInfo(&jwsDevBaseInfo);
    for (i = 1; i <= jwsDevBaseInfo.port_num; i++)
    {
        jwsQosPortConfigTable_createEntry(i);
    }
}

    /* Typical data structure for a row entry */
struct jwsQosPortConfigTable_entry {
    /* Index values */
//    long jwsQosPortIndex;

    /* Column values */
    long jwsQosPortIndex;
    long jwsQosPortPrioAssignMode;
    long old_jwsQosPortPrioAssignMode;
    long jwsQosPortPrioMapRule;
    long old_jwsQosPortPrioMapRule;
    long jwsQosPortDefaultPrioLevel;
    long old_jwsQosPortDefaultPrioLevel;
    long jwsQosPortSchedulingMode;
    long old_jwsQosPortSchedulingMode;

    /* Illustrate using a simple linked list */
    int   valid;
    struct jwsQosPortConfigTable_entry *next;
};

struct jwsQosPortConfigTable_entry  *jwsQosPortConfigTable_head;

/* create a new row in the (unsorted) table */
struct jwsQosPortConfigTable_entry *
jwsQosPortConfigTable_createEntry(
                 long  jwsQosPortIndex
                ) {
    struct jwsQosPortConfigTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct jwsQosPortConfigTable_entry);
    if (!entry)
        return NULL;

    entry->jwsQosPortIndex = jwsQosPortIndex;
    entry->next = jwsQosPortConfigTable_head;
    jwsQosPortConfigTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
jwsQosPortConfigTable_removeEntry( struct jwsQosPortConfigTable_entry *entry ) {
    struct jwsQosPortConfigTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = jwsQosPortConfigTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        jwsQosPortConfigTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
jwsQosPortConfigTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = jwsQosPortConfigTable_head;
    return jwsQosPortConfigTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
jwsQosPortConfigTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct jwsQosPortConfigTable_entry *entry = (struct jwsQosPortConfigTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->jwsQosPortIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the jwsQosPortConfigTable table */
int
jwsQosPortConfigTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct jwsQosPortConfigTable_entry          *table_entry;

    int ret;
    int data;
    char str[100] = {0};
    char value[50];

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsQosPortConfigTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            bzero(str, sizeof(str));
    
            switch (table_info->colnum) {
            case COLUMN_JWSQOSPORTINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsQosPortIndex);
                break;
            case COLUMN_JWSQOSPORTPRIOASSIGNMODE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_qos_port_cmd_enc(str, sizeof(str), table_entry->jwsQosPortIndex, 
                                "port_priority_assignment");
                ret = ubus_invoke_command("qos_config", "qos_config_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsQosPortPrioAssignMode = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsQosPortPrioAssignMode);
                break;
            case COLUMN_JWSQOSPORTPRIOMAPRULE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_qos_port_cmd_enc(str, sizeof(str), table_entry->jwsQosPortIndex, 
                                "port_priority_map_rule");
                ret = ubus_invoke_command("qos_config", "qos_config_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsQosPortPrioMapRule = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsQosPortPrioMapRule);
                break;
            case COLUMN_JWSQOSPORTDEFAULTPRIOLEVEL:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_qos_port_cmd_enc(str, sizeof(str), table_entry->jwsQosPortIndex, 
                                "port_default_priority_level");
                ret = ubus_invoke_command("qos_config", "qos_config_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsQosPortDefaultPrioLevel = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsQosPortDefaultPrioLevel);
                break;
            case COLUMN_JWSQOSPORTSCHEDULINGMODE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_qos_port_cmd_enc(str, sizeof(str), table_entry->jwsQosPortIndex, 
                                "port_schedule_mode");
                ret = ubus_invoke_command("qos_config", "qos_config_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsQosPortSchedulingMode = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsQosPortSchedulingMode);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsQosPortConfigTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSQOSPORTPRIOASSIGNMODE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSQOSPORTPRIOMAPRULE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSQOSPORTDEFAULTPRIOLEVEL:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_JWSQOSPORTSCHEDULINGMODE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsQosPortConfigTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            bzero(str, sizeof(str));
    
            switch (table_info->colnum) {
            case COLUMN_JWSQOSPORTPRIOASSIGNMODE:
                table_entry->old_jwsQosPortPrioAssignMode = table_entry->jwsQosPortPrioAssignMode;
                table_entry->jwsQosPortPrioAssignMode     = *request->requestvb->val.integer;

                snprintf(value, sizeof(value), "%ld", table_entry->jwsQosPortPrioAssignMode);
                ubus_set_qos_port_cmd_enc(str, sizeof(str), 
                    table_entry->jwsQosPortIndex, "port_priority_assignment", value);
                ret = ubus_invoke_command("qos_config", "qos_config_set", 
                                    set_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSQOSPORTPRIOMAPRULE:
                table_entry->old_jwsQosPortPrioMapRule = table_entry->jwsQosPortPrioMapRule;
                table_entry->jwsQosPortPrioMapRule     = *request->requestvb->val.integer;

                snprintf(value, sizeof(value), "%ld", table_entry->jwsQosPortPrioMapRule);
                ubus_set_qos_port_cmd_enc(str, sizeof(str), 
                    table_entry->jwsQosPortIndex, "port_priority_map_rule", value);
                ret = ubus_invoke_command("qos_config", "qos_config_set", 
                                    set_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSQOSPORTDEFAULTPRIOLEVEL:
                table_entry->old_jwsQosPortDefaultPrioLevel = table_entry->jwsQosPortDefaultPrioLevel;
                table_entry->jwsQosPortDefaultPrioLevel     = *request->requestvb->val.integer;

                snprintf(value, sizeof(value), "%ld", table_entry->jwsQosPortDefaultPrioLevel);
                ubus_set_qos_port_cmd_enc(str, sizeof(str), 
                    table_entry->jwsQosPortIndex, "port_default_priority_level", value);
                ret = ubus_invoke_command("qos_config", "qos_config_set", 
                                    set_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            case COLUMN_JWSQOSPORTSCHEDULINGMODE:
                table_entry->old_jwsQosPortSchedulingMode = table_entry->jwsQosPortSchedulingMode;
                table_entry->jwsQosPortSchedulingMode     = *request->requestvb->val.integer;

                snprintf(value, sizeof(value), "%ld", table_entry->jwsQosPortSchedulingMode);
                ubus_set_qos_port_cmd_enc(str, sizeof(str), 
                    table_entry->jwsQosPortIndex, "port_schedule_mode", value);
                ret = ubus_invoke_command("qos_config", "qos_config_set", 
                                    set_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsQosPortConfigTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSQOSPORTPRIOASSIGNMODE:
                table_entry->jwsQosPortPrioAssignMode     = table_entry->old_jwsQosPortPrioAssignMode;
                table_entry->old_jwsQosPortPrioAssignMode = 0;
                break;
            case COLUMN_JWSQOSPORTPRIOMAPRULE:
                table_entry->jwsQosPortPrioMapRule     = table_entry->old_jwsQosPortPrioMapRule;
                table_entry->old_jwsQosPortPrioMapRule = 0;
                break;
            case COLUMN_JWSQOSPORTDEFAULTPRIOLEVEL:
                table_entry->jwsQosPortDefaultPrioLevel     = table_entry->old_jwsQosPortDefaultPrioLevel;
                table_entry->old_jwsQosPortDefaultPrioLevel = 0;
                break;
            case COLUMN_JWSQOSPORTSCHEDULINGMODE:
                table_entry->jwsQosPortSchedulingMode     = table_entry->old_jwsQosPortSchedulingMode;
                table_entry->old_jwsQosPortSchedulingMode = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
//  # Determine the first/last column names

/** Initialize the jwsQosPriority8021pTable table by defining its contents and how it's structured */
void
initialize_table_jwsQosPriority8021pTable(void)
{
    static oid jwsQosPriority8021pTable_oid[] = {1,3,6,1,4,1,33444,2,2,5,1,2};
    size_t jwsQosPriority8021pTable_oid_len   = OID_LENGTH(jwsQosPriority8021pTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    int i;

    reg = netsnmp_create_handler_registration(
              "jwsQosPriority8021pTable",     jwsQosPriority8021pTable_handler,
              jwsQosPriority8021pTable_oid, jwsQosPriority8021pTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: jwsQos8021pPriorityIndex */
                           0);
    table_info->min_column = COLUMN_JWSQOS8021PPRIORITYINDEX;
    table_info->max_column = COLUMN_JWSQOS8021PPRIORITYQUEUEID;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = jwsQosPriority8021pTable_get_first_data_point;
    iinfo->get_next_data_point  = jwsQosPriority8021pTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
    for (i = 0; i <= 7; ++i)
    {
        jwsQosPriority8021pTable_createEntry(i);
    }
}

    /* Typical data structure for a row entry */
struct jwsQosPriority8021pTable_entry {
    /* Index values */
//    long jwsQos8021pPriorityIndex;

    /* Column values */
    long jwsQos8021pPriorityIndex;
    long jwsQos8021pPriorityQueueId;
    long old_jwsQos8021pPriorityQueueId;

    /* Illustrate using a simple linked list */
    int   valid;
    struct jwsQosPriority8021pTable_entry *next;
};

struct jwsQosPriority8021pTable_entry  *jwsQosPriority8021pTable_head;

/* create a new row in the (unsorted) table */
struct jwsQosPriority8021pTable_entry *
jwsQosPriority8021pTable_createEntry(
                 long  jwsQos8021pPriorityIndex
                ) {
    struct jwsQosPriority8021pTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct jwsQosPriority8021pTable_entry);
    if (!entry)
        return NULL;

    entry->jwsQos8021pPriorityIndex = jwsQos8021pPriorityIndex;
    entry->next = jwsQosPriority8021pTable_head;
    jwsQosPriority8021pTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
jwsQosPriority8021pTable_removeEntry( struct jwsQosPriority8021pTable_entry *entry ) {
    struct jwsQosPriority8021pTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = jwsQosPriority8021pTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        jwsQosPriority8021pTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
jwsQosPriority8021pTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = jwsQosPriority8021pTable_head;
    return jwsQosPriority8021pTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
jwsQosPriority8021pTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct jwsQosPriority8021pTable_entry *entry = (struct jwsQosPriority8021pTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->jwsQos8021pPriorityIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the jwsQosPriority8021pTable table */
int
jwsQosPriority8021pTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct jwsQosPriority8021pTable_entry          *table_entry;

    int ret;
    int data;
    char str[100] = {0};
    char value[50];

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsQosPriority8021pTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            bzero(str, sizeof(str));
    
            switch (table_info->colnum) {
            case COLUMN_JWSQOS8021PPRIORITYINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsQos8021pPriorityIndex);
                break;
            case COLUMN_JWSQOS8021PPRIORITYQUEUEID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_qos_8021p_cmd_enc(str, sizeof(str), table_entry->jwsQos8021pPriorityIndex, 
                                "8021p_priority_queue_id");
                ret = ubus_invoke_command("qos_config", "qos_config_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsQos8021pPriorityQueueId = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsQos8021pPriorityQueueId);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsQosPriority8021pTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSQOS8021PPRIORITYQUEUEID:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsQosPriority8021pTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            bzero(str, sizeof(str));
    
            switch (table_info->colnum) {
            case COLUMN_JWSQOS8021PPRIORITYQUEUEID:
                table_entry->old_jwsQos8021pPriorityQueueId = table_entry->jwsQos8021pPriorityQueueId;
                table_entry->jwsQos8021pPriorityQueueId     = *request->requestvb->val.integer;

                snprintf(value, sizeof(value), "%ld", table_entry->jwsQos8021pPriorityQueueId);
                ubus_set_qos_8021p_cmd_enc(str, sizeof(str), 
                    table_entry->jwsQos8021pPriorityIndex, "8021p_priority_queue_id", value);
                ret = ubus_invoke_command("qos_config", "qos_config_set", 
                                    set_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsQosPriority8021pTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSQOS8021PPRIORITYQUEUEID:
                table_entry->jwsQos8021pPriorityQueueId     = table_entry->old_jwsQos8021pPriorityQueueId;
                table_entry->old_jwsQos8021pPriorityQueueId = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
//  # Determine the first/last column names

/** Initialize the jwsQosPriorityDscpTable table by defining its contents and how it's structured */
void
initialize_table_jwsQosPriorityDscpTable(void)
{
    static oid jwsQosPriorityDscpTable_oid[] = {1,3,6,1,4,1,33444,2,2,5,1,3};
    size_t jwsQosPriorityDscpTable_oid_len   = OID_LENGTH(jwsQosPriorityDscpTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    int i;

    reg = netsnmp_create_handler_registration(
              "jwsQosPriorityDscpTable",     jwsQosPriorityDscpTable_handler,
              jwsQosPriorityDscpTable_oid, jwsQosPriorityDscpTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: jwsQosDscpPriorityIndex */
                           0);
    table_info->min_column = COLUMN_JWSQOSDSCPPRIORITYINDEX;
    table_info->max_column = COLUMN_JWSQOSDSCPPRIORITYQUEUEID;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = jwsQosPriorityDscpTable_get_first_data_point;
    iinfo->get_next_data_point  = jwsQosPriorityDscpTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
    for (i = 0; i <= 63; ++i)
    {
        jwsQosPriorityDscpTable_createEntry(i);
    }
}

    /* Typical data structure for a row entry */
struct jwsQosPriorityDscpTable_entry {
    /* Index values */
//    long jwsQosDscpPriorityIndex;

    /* Column values */
    long jwsQosDscpPriorityIndex;
    long jwsQosDscpPriorityQueueId;
    long old_jwsQosDscpPriorityQueueId;

    /* Illustrate using a simple linked list */
    int   valid;
    struct jwsQosPriorityDscpTable_entry *next;
};

struct jwsQosPriorityDscpTable_entry  *jwsQosPriorityDscpTable_head;

/* create a new row in the (unsorted) table */
struct jwsQosPriorityDscpTable_entry *
jwsQosPriorityDscpTable_createEntry(
                 long  jwsQosDscpPriorityIndex
                ) {
    struct jwsQosPriorityDscpTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct jwsQosPriorityDscpTable_entry);
    if (!entry)
        return NULL;

    entry->jwsQosDscpPriorityIndex = jwsQosDscpPriorityIndex;
    entry->next = jwsQosPriorityDscpTable_head;
    jwsQosPriorityDscpTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
jwsQosPriorityDscpTable_removeEntry( struct jwsQosPriorityDscpTable_entry *entry ) {
    struct jwsQosPriorityDscpTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = jwsQosPriorityDscpTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        jwsQosPriorityDscpTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
jwsQosPriorityDscpTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = jwsQosPriorityDscpTable_head;
    return jwsQosPriorityDscpTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
jwsQosPriorityDscpTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct jwsQosPriorityDscpTable_entry *entry = (struct jwsQosPriorityDscpTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->jwsQosDscpPriorityIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the jwsQosPriorityDscpTable table */
int
jwsQosPriorityDscpTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct jwsQosPriorityDscpTable_entry          *table_entry;

    int ret;
    int data;
    char str[100] = {0};
    char value[50];

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsQosPriorityDscpTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSQOSDSCPPRIORITYINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsQosDscpPriorityIndex);
                break;
            case COLUMN_JWSQOSDSCPPRIORITYQUEUEID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                ubus_get_qos_dscp_cmd_enc(str, sizeof(str), table_entry->jwsQosDscpPriorityIndex, 
                                "dscp_priority_queue_id");
                ret = ubus_invoke_command("qos_config", "qos_config_get", 
                                        get_table_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }
                data = atoi(jws_read_buf_str());
                table_entry->jwsQosDscpPriorityQueueId = data;

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->jwsQosDscpPriorityQueueId);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsQosPriorityDscpTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSQOSDSCPPRIORITYQUEUEID:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsQosPriorityDscpTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            bzero(str, sizeof(str));
    
            switch (table_info->colnum) {
            case COLUMN_JWSQOSDSCPPRIORITYQUEUEID:
                table_entry->old_jwsQosDscpPriorityQueueId = table_entry->jwsQosDscpPriorityQueueId;
                table_entry->jwsQosDscpPriorityQueueId     = *request->requestvb->val.integer;

                snprintf(value, sizeof(value), "%ld", table_entry->jwsQosDscpPriorityQueueId);
                ubus_set_qos_dscp_cmd_enc(str, sizeof(str), 
                    table_entry->jwsQosDscpPriorityIndex, "dscp_priority_queue_id", value);
                ret = ubus_invoke_command("qos_config", "qos_config_set", 
                                    set_ret_handler_cb, str);
                if (ret != 0)
                {
                    return SNMP_ERR_NOSUCHNAME;
                }

                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct jwsQosPriorityDscpTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_JWSQOSDSCPPRIORITYQUEUEID:
                table_entry->jwsQosDscpPriorityQueueId     = table_entry->old_jwsQosDscpPriorityQueueId;
                table_entry->old_jwsQosDscpPriorityQueueId = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
