#./build_cpss.sh MSYS DX_ALL UTF_NO  NOKERNEL CPSS_ENABLER  SHLIB  NOGALTIS CUST
#./build_cpss.sh MSYS DX_ALL UTF_NO  NOKERNEL CPSS_ENABLER  SHLIB NOGALTIS NOLUA CUST
#./build_cpss.sh MSYS DX_ALL UTF_NO  NOKERNEL  CUST
# ./build_cpss.sh MSYS DX_ALL UTF_NO  NOKERNEL CPSS_ENABLER  SO_LIB NOGALTIS CUST

./build_cpss.sh MSYS DX_ALL UTF_NO  NOKERNEL CPSS_ENABLER  SHLIB NOLUA  NOGALTIS CUST
